### ISSUE TITLE
Can't get esmock to work

### ISSUE THREAD

**Issue by alucryd** [iambumblehead/esmock#109]
Hi there, I'm probably using esmock wrong, but I can't seem to get it to work. I'm trying to test an express app with jest and supertest, but since jest doesn't support esm I turned to esmock for my mocking needs.

Here's my project layout:
![image](https://user-images.githubusercontent.com/1561084/184309216-b8a31011-07b7-4140-b803-cb5aee91b4e2.png)

So I came up with the following:

```
const app = await esmock.px('../../../../src/app.js', {
  '../../../../src/routes/v1/index.js': {
    '../../../../src/routes/v1/purchaseOrders.js': {
      '../../../../src/services/v1/interfaces.js': {
        getByEnvelopeTableName: async (envelopeTableName) => {
          return new Interface(1234, 4321, envelopeTableName);
        },
      },
    },
  },
});
```

The `interfaces.js` service contains a single exported async function that calls a database, that's the one I'm trying to mock. That function is imported in the `purchaseOrders.js` router like this:

```
import { getByEnvelopeTableName as getInterfaceByEnvelopeTableName } from '../../services/v1/interfaces.js';
```

However when I debug my test, I see that the original function is still there instead of being mocked. Do you have any idea where I might be missing something?

**Comment by iambumblehead** [comment]
@alucryd try using esmock this way with jest-light-runner. The third parameter to esmock applies mock definitions "deeply" to app.js' returned import tree
```javascript
const app = await esmock.px('../../../../src/app.js', null, {
  '../../../../src/services/v1/interfaces.js': {
    getByEnvelopeTableName: async (envelopeTableName) => {
      return new Interface(1234, 4321, envelopeTableName);
    }
  }
});
```

**Comment by iambumblehead** [comment]
@alucryd if 'getByEnvelopeTableName' is a member of 'default' try something like this
```javascript
const app = await esmock.px('../../../../src/app.js', null, {
  '../../../../src/services/v1/interfaces.js': {
    default: {
      getByEnvelopeTableName: async (envelopeTableName) => {
        return new Interface(1234, 4321, envelopeTableName);
      }
    }
  }
});
```

**Comment by alucryd** [comment]
Your first suggestion with jest-light-runner worked like a charm, thank you!
