### ISSUE TITLE
esmock.d.ts export incorrect

### ISSUE THREAD

**Issue by jakebailey** [iambumblehead/esmock#110]
I tried importing `esmock` and got:

> This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

It looks like this `d.ts` file is handwritten; rather than what it currently says:

```ts
declare function esmock(path: string, localmock?: any, globalmock?: any): any;
export = esmock;
```

I believe this should actually read:

```ts
declare function esmock(path: string, localmock?: any, globalmock?: any): any;
export default esmock;
```

Which matches what TS would output for the code you've written in your `js` file. [Playground Link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAphAtiYBrGBeGBDCBPMYGACgAdsoALALhmgCcBLMAcwBoYAbFbT5NAPy1sYPBxbcARr36ohOUQEpMAPhgBvAL4BuAFBwAHqRD1YAEzgAzbAFdOsBLO1A)

**Comment by iambumblehead** [comment]
@jakebailey would you make a PR? I would do this but am in the middle of something atm

**Comment by jakebailey** [comment]
Sent #111.

(It'd be cool for this to be in TS from the start, or have a more complete d.ts file, but that's a different problem than me not being able to import it from my code at all.)

**Comment by iambumblehead** [comment]
We're in the process of dramatically improving the interpretation of esm import and export patterns and the changes should be ready in a few days. Please open an issue if you find anything in the current version of the package.

The PR will be published soonish -- thank you :)

**Comment by iambumblehead** [comment]
@jakebailey it is published https://github.com/iambumblehead/esmock/releases/tag/v1.9.3

**Comment by jakebailey** [comment]
Thanks, it's working now! (Besides a bug with relative module paths, which I'll try to report somehow.)

**Comment by iambumblehead** [comment]
@jakebailey hopefully a solution will come soon thanks for making this package better
