### ISSUE TITLE
esmock fails if source maps are used

### ISSUE THREAD

**Issue by jakebailey** [iambumblehead/esmock#113]
I have a TS project using ava on TS's output. I have to do this as my project calls into `import.meta.resolve` / `import-meta-resolve`, and I want to test on my project as it ships to users. I have source maps enabled so that I can debug / run coverage on my tests.

Unfortunately, esmock doesn't seem to work if source maps are enabled.

Here's a minimal repro: https://github.com/jakebailey/esmock-source-map-bug

I suspect it's due to this: https://github.com/iambumblehead/esmock/blob/31cc29825c0717f6979cf4fb78b247f514b1f37c/src/esmock.js#L12

If source maps have been loaded, the backtrace will show the mapped location (my TS src dir), not the true location (a dist dir of compiled code). Maybe esmock's API should accept a `parent` parameter so that the caller can pass `import.meta.url`, similar to `import-meta-resolve` or other ESM-y APIs?

**Comment by iambumblehead** [comment]
If esmock's interface is updated to support a 'parent' value defined in the fourth parameter, would that be a good solution? what do you recommend?
```javascript
const indexModule = await esmock("../index.js", {
  os: {
    hostname: () => expectedHostname,
  },
}, null, {
  parent: parentURL
});
```

**Comment by jakebailey** [comment]
It'd be an API break, but I would think this would be a required parameter, and "callePath" ceases to be automatically detected.

**Comment by jakebailey** [comment]
Just for reference for anyone finding this, my current workaround is this:

```ts
import { fileURLToPath } from "url";

export function fixESMockPath(path: string, importMetaUrl: string): string {
    const url = new URL(path, importMetaUrl);
    return fileURLToPath(url);
```

Then, when testing:

```ts
import test from "ava";
import esmock from "esmock";

import { fixESMockPath } from "./testUtils.js";
import type * as myModuleType from "../myModule.js";

test("do something", async (t) => {
    const myModule: typeof myModuleType = await esmock(fixESMockPath("../myModule.js", import.meta.url), {
        fs: {
            writeFile: () => { ... }
        },
        [fixESMockPath("../localLib.js", import.meta.url)]: {
            someFunction: () => { ... }
        },
    };

    const result = await myModule.doSomething(); // Run with the above modules mocked.
    t.is(result, 1234);
});

**Comment by iambumblehead** [comment]
resolved here https://github.com/iambumblehead/esmock/pull/122 closing
