### ISSUE TITLE
Issue with partially mocking module that is also used within same file by another module

### ISSUE THREAD

**Issue by vueme** [iambumblehead/esmock#118]
Hello.

I think I've found an issue. I'm having trouble with partially mocking deeply nested module that is also used in same file. Example below. I'm on Mocha and Node 17.4.0.

```
const supertestModule = await esmock.px('../modules/supertest.js', null, {
  '../../../../server/troublesomeFile.js': {
    funcOne: async () => {
      console.log('Ran')
    }
  }
})
```

troublesomeFile.js
```
export async function funcOne() {
  console.log('Should not be called')
}

export async function funcTwoSameFile() {
   const test = await funcOne()
  
  // some more code
  
  return test
}
```

supertest.js (might not be relevant)
```
// imports app.js...
export default async () => {
     // More code...

     return supertest(app)
      .post(`/v1/${endpoint}`)
      .set({ ...thingsToSet })
      .send({ ...requestBody })
  }
}
```

When funcTwoSameFile is called somewhere deeply nested in app.js, original version of funcOne is called and not the mocked one. Is this some kind of limitation or am i missing something? My other (full-module, not .px mocks) are working fine in other tests.

Thanks for your help!

**Comment by iambumblehead** [comment]
https://github.com/iambumblehead/esmock/blob/master/src/esmockModule.js#L97-L98

@vueme esmock currently does something like this paraphrased example,
```javascript
const originalFile = import( pathtooriginalfile );
const mockedFile = Object.assign({}, originalFile, mockDefinitions);

return mockedFile
```
and so the partial mock won't work for your use-case (sorry)

is it OK with you if this ticket is closed?

**Comment by vueme** [comment]
Thanks for quick answer!

You do not happen to have any workaround recommendation?

Thanks anyways!

**Comment by iambumblehead** [comment]
@vueme these may not be great ideas but here they are :) One idea is to define both mock functions at the same time eg,
```javascript
const mock = {};
mock.funcTwo = () => 'mocked func two';
mock.funcOne = () => mock.funcTwo();

const supertestModule = await esmock.px('../modules/supertest.js', null, {
  '../../../../server/troublesomeFile.js': mock
})
```

another idea is to use 'this' or some other namespace creatively like this
_originalfile.js_
```javascript
export const obj = {};

obj.funcOne = async function () {
  return 'this.funcOne'
};
obj.funcTwo = async function () {
  return await this.funcOne();
};
```

_originalfile-test.js_
```javascript
const supertestModule = await esmock.px('../modules/supertest.js', null, {
  '../../../../server/troublesomeFile.js': {
     obj: {
       ...troublesomefile.obj,
       funcOne: () => 'mocked value'
     }
   }
})
```
I didn't test these but hope their intention is expressed

**Comment by vueme** [comment]
Thanks for the ideas and this great js package! I'll look into this.
