### ISSUE TITLE
Seems to fail with pg

### ISSUE THREAD

**Issue by TrashBinNp2019** [iambumblehead/esmock#119]
```
const client = await esmock(
  '../src/client.ts',
  {
    'pg': {
      Pool: (config:any) => {
      },
    },
  },
);
```
Results in a 
```
Error: not a valid path: "pg" (used by
.../test/client.ts)
```

**Comment by iambumblehead** [comment]
thanks for finding and sharing this issue. I'll try to resolve it

**Comment by iambumblehead** [comment]
the resolver test is passing now https://github.com/iambumblehead/resolvewithplus/pull/32

the resolver is soon to get a big update and its great to add this extra test case there

**Comment by iambumblehead** [comment]
@TrashBinNp2019 would you verify if the published solution resolves the issue for you? https://github.com/iambumblehead/esmock/releases/tag/v1.9.5

**Comment by TrashBinNp2019** [comment]
Yup, all is good. Thanks a lot for quick response. Closing

**Comment by head-gardener** [comment]
great, thanks a lot for quick response

пт, 19 авг. 2022 г., 18:08 iambumblehead ***@***.***>:
