### ISSUE TITLE
Can I edit existing functions with esmock?

### ISSUE THREAD

**Issue by TimDaub** [iambumblehead/esmock#12]
Say I have a module

./to/module.js
```
export function add(a, b) { return a+b} 
```

and then another that uses esmock

```
import esmock from 'esmock';
await esmock('./to/module.js', {add: () => console.log('hello')}, globalmocks)
```
Will this too work? Or is esmock just mocking imports?

**Comment by iambumblehead** [comment]
@TimDaub hello and thank you for the star :). It only mocks the imports.

feel free to re-open if necessary
