### ISSUE TITLE
Can't mock package 'vue' if it doesn't installed

### ISSUE THREAD

**Issue by cawa-93** [iambumblehead/esmock#126]
My case: I have generated package like below:
```js
import {h} from 'vue';
export const ComponentName = () => h('svg', { /* some properties */ });
```
And I want to test this package. The point of the test is just to check that function `h` was called with the correct parameters.

So I tried mock `h` function from `vue`
```js
// test.spec.js
const component= await esmock(`../component.js`, {}, {
  vue: {
    h: (...args) => args
  }
})
```

It works great. But, only if the `vue` is installed as a dependency. Because in reality no `vue` functionality is used anywhere, I tried to remove this dependency, but then I get the error:

```
not a valid path: "vue" 
```

What can I do about it? I wouldn't want to install an entire framework just to mock a single function in tests.

**You can reproduce the problem**
1. Clone repo: `git clone https://github.com/cawa-93/iconify-prerendered.git`
2. Delete `vue` dependency: `npm un vue`
3. Install others dependencies: `npm ci`
4. Generate code for testing: `npm run build`
5. Run test: `npm run test`

**Comment by iambumblehead** [comment]
this is an interesting scenario I did not think of @cawa-93

**Comment by iambumblehead** [comment]
another suggestion on could try, write a file like this before running the test "./node_modules/vue/index.js" this would probably be located by node as a cjs module which would make the error go away

**Comment by cawa-93** [comment]
@iambumblehead This loader works for me
```js
import module from 'module'

// Resolve unexisting package
export async function resolve(specifier, context, nextResolve) {
  if (specifier === 'vue') {
    return {
      shortCircuit: true,
      url: specifier
    };
  }
  return nextResolve(specifier, context);
}

// Load unexisting package
export function load(url, context, nextLoad) {
  if (url === 'vue') {
    return {
      format: 'module',
      shortCircuit: true,
      source: `export const h = (...args) => args`, // <- moke code
    }
  }

  return nextLoad(url, context);
}
```

**Comment by iambumblehead** [comment]
@cawa-93 awesome ok let's try to update esmock. Do you need a solution now or is it ok if day or two go by before changes are made?

**Comment by iambumblehead** [comment]
the soonest I could look into this myself is maybe 7 or 8 hours from now

**Comment by cawa-93** [comment]
Ok. I will try to make pr ASAP. A few days, I think

**Comment by iambumblehead** [comment]
@cawa-93 if there is a PR with passing tests it can be merged and published as soon as its ready

**Comment by cawa-93** [comment]
After thinking again, I think I won't find enough time to figure it out and make a change. In any case, you can do it faster (although, personally, these changes are not urgent for me). Therefore, I will leave PR to you. Thanks again for the quick response.

**Comment by iambumblehead** [comment]
@cawa-93 please confirm if this resolves the issue for you https://github.com/iambumblehead/esmock/releases/tag/v1.9.7

if you think the interface should be changed or have any criticisms or suggestions feel free to give your opinion

**Comment by cawa-93** [comment]
@iambumblehead It's work like a charm ✨ Thanks
Did you forget to add a new `isPackageNotFoundError` parameter to the type declaration?
https://github.com/iambumblehead/esmock/blob/968b357d6b3930134e0b7efbc12f5b2fcacbb36b/src/esmock.d.ts#L22-L25

**Comment by iambumblehead** [comment]
@cawa-93 yes I did forget
