### ISSUE TITLE
Imports Aren't Mocked; Using Mocha, Sinon, Assert

### ISSUE THREAD

**Issue by Swivelgames** [iambumblehead/esmock#13]
**Versions:**
- **node**: v16.7.0
- **esmock**: v0.3.9
- **mocha**: v9.0.3
- **sinon**: v11.1.2
- **c8**: v7.8.0

After running `npm i`, run: `npm run test` to get the error.
I'm attempting to mock an import, but it doesn't seem to be doing anything. I've tried everything, including just setting the `default` mock to return `class {}`, and it still throws the same error.

Here's a repo that can consistently reproduce the issue: https://github.com/Swivelgames/_esmock_issues_13

The error tells me that it's **_actually doing something_** (unlike most of the other mock libraries I've come across that claim ESM support), which is great! And if I can get passed this issue, I should be home free!

```
> esmock-issue@1.0.0 test
> npx mocha --loader=esmock --config ./.mocharc.jsonc

(node:1137639) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)


  MyClassWrapper
    constructor()
      1) should mock imports


  0 passing (15ms)
  1 failing

  1) MyClassWrapper
       constructor()
         should mock imports:
     TypeError: MyClass is not a constructor
      at new MyClassWrapper (file:///******/src/index.js?key=1?esmockGlobals=null#esmockModuleKeys=file:///******/src/class.js?esmockKey=1&esmockModuleKey=./class.js&isesm=true&exportNames=default:5:20)
      at Context.<anonymous> (file:///******/src/index.test.js:23:16)
```

This is probably more like a support post than an actual issue. But, any thoughts?

**Comment by Swivelgames** [comment]
Here's a direct link to my test file: https://github.com/Swivelgames/_esmock_issues_13/blob/master/src/index.test.js

```javascript
import esmock from "esmock";
import assert from "assert";
import sinon from "sinon";

import MyClass from "./class.js";

import { createMockClassImport } from "../test-utils.js"

const {
	mockClass,
	mockConstructor
} = createMockClassImport(MyClass);

describe("MyClassWrapper", () => {
	describe("constructor()", () => {
		it("should mock imports", async () => {
			const MyClassWrapper = await esmock("./index.js", {
				"./class.js": {
					default: () => mockClass
				}
			});

			const api = new MyClassWrapper();
			assert.ok(!!mockConstructor.lastCall);
		});
	});
});
```

**Comment by Swivelgames** [comment]
HAH. Figured out the issue.

Instead of:

```javascript
"./class.js": {
    default: () => mockClass
}
```
I needed to do:
```javascript
"./class.js": {
    default: mockClass
}
```

**Comment by iambumblehead** [comment]
@Swivelgames I'm glad its working
