### ISSUE TITLE
How to mock class ?

### ISSUE THREAD

**Issue by iggyzap** [iambumblehead/esmock#137]
Let's consider following source file:
```foo.js
import { SecretsManager} from "@aws-sdk/client-secrets-manager";

const { REGION, SECRET_ID } = process.env;

const secretsManager = new SecretsManager({ region: REGION });

export async function handler () {
    return await secretsManager.listSecrets()
}
```

And unit test for it:
```foo.unit.js
import esmock from "esmock";
import {jest} from "@jest/globals";

const mocks = {}
const awsSdk = `@aws-sdk/client-secrets-manager`
mocks[awsSdk] = {
    SecretsManager: {
       constructor: jest.fn()
    }

}

const foo = await esmock("./foo.js", mocks)

describe("Foo", () => {
    it("Foo defined", () => {
        expect(foo).toBeDefined();
    })

    it("List secrets called on handler", async () => {

        await foo.handler()
    })
})
```

Unfortunately secrets manager when instantiated with constructor is not mocked, but presented as actual class.
What is the guideline how to mock it ? Is there additional information that I can provide to diagnose ?

Please forgive me if SecretsManager source is coming from typescript and it seems that by default it is resolving to dist-cjs source files :/

I am invoking jest with following:
`NODE_OPTIONS="--loader=esmock --experimental-vm-modules" jest --config jest.config.cjs`

**Comment by iambumblehead** [comment]
@iggyzap to use --loader with jest, jest-light-runner must be used, as in [the example test here](https://github.com/iambumblehead/esmock/blob/master/tests/tests-jest/package.json)

Try using jest-light-runner and if things still aren't working, message back we'll get it working. We could add your example test to the test-folder [in the link here](https://github.com/iambumblehead/esmock/blob/master/tests/tests-jest/) and make a PR that gets everything working.

Thanks for opening the issue :)

**Comment by iambumblehead** [comment]
maybe the wiki should be updated with more details about jest-light-runner

**Comment by iggyzap** [comment]
I've got it working. Wonder if it's possible to automock classes, without explicitly declaring them ?

See steps below:

1. setting `jest` runner to be `jest-light-runner`
2. using NODE_OPTIONS for the loader: `NODE_OPTIONS="--loader=esmock --experimental-vm-modules" jest --config jest.config.cjs`
4. Javascript which imports library:
```foo.js
import {SecretsManager} from "@aws-sdk/client-secrets-manager";

const secretsManager = new SecretsManager({});

export async function secrets() {
    return await secretsManager.listSecrets({})
}
```
5. Test code that validates that `listSecrets()` was called:
```foo.unit.js
import esmock from "esmock";

const mocks = {}

const awsSdk1 = `@aws-sdk/client-secrets-manager`

class MockCl1{
    listSecrets() {
        mockMethod()
    }
}

mocks[awsSdk1] = {
    SecretsManager:MockCl1
}

const mockMethod = jest.fn()

const foo = await esmock("./foo.js", mocks)

describe("Foo", () => {
    it("Foo defined", () => {
        expect(foo).toBeDefined();
    })

    it("List secrets called on handler", async () => {

        await foo.secrets()
        expect(mockMethod).toHaveBeenCalled()
    })
})
```

**Comment by iambumblehead** [comment]
Thanks for sharing the successful steps. As for auto-mocking, maybe something like one of the below could be used. These aren't tested and I'm not sure what use cases your tests need to solve...
```javascript
const foo = await esmock("./foo.js", {
  "@aws-sdk/client-secrets-manager": {
    SecretsManager: (() => (
      class MockCl1{
        listSecrets() {
          mockMethod()
        }
      }
    ))()
  }
})
```
Or maybe a factory that generates a different versions of the foo.js import tree with different instances of client-secrets-manager mock,
```javascript
const foo = async () => (
  esmock("./foo.js", {
    "@aws-sdk/client-secrets-manager": {
      SecretsManager: (() => (
        class MockCl1{
          listSecrets() {
            mockMethod()
          }
        }
      ))()
    }
  })
)

const foo1 = foo()
const foo2 = foo()
```

if the issue resolved overall, please close this issue :)

**Comment by iggyzap** [comment]
Actually, nice way to have narrow scope for the module under test :)

> // inside test1
> const foo1 = await foo()
> 
> // inside test2
> const foo2 = await foo()
> ```
> 
> if the issue resolved overall, please close this issue :)
