### ISSUE TITLE
Partial mocking of module under test

### ISSUE THREAD

**Issue by iggyzap** [iambumblehead/esmock#138]
Let's consider a scenario when we want to have a number of methods within a module replaced by mocks but want to test a specific method and it's interactions and don't want to extract these _helper_ methods into different javascript file.

Is that something achievable with current version of esmock ?

Example:
```foo.js
export async function handler() {
  doBark();
}

async function doBark() {
  return "Wooof!"
}
```

And test:

```foo.test.js

import esmock from "esmock";

const mocks = {}

mocks['./foo.js'] = {
    otherFn: mockMethod
}

const mockMethod = jest.fn()

const foo = await esmock("./foo.js", mocks)

describe("Foo", () => {
    it("Foo defined", () => {
        expect(foo).toBeDefined();
    })


    it("Mock out internal function", async () => {

        await foo.some()
        expect(mockMethod).toHaveBeenCalled()
    })

})
```

**Comment by iambumblehead** [comment]
I don't think it is achievable with esmock. See this discussion here https://github.com/iambumblehead/esmock/issues/118#issuecomment-1216948048
