### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in [...]/node_modules/esmock/package.json

### ISSUE THREAD

**Issue by ericmorand** [iambumblehead/esmock#152]
Importing esmock@2.0.1 leads to the following error:

`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in [...]/node_modules/esmock/package.json`

```ts
// @ts-ignore
import esmock from "esmock";

esmock('./foo', {]);
```

**Comment by iambumblehead** [comment]
@ericmorand would you give more information about your setup so that I can reproduce the issue?

Is there another "export" definition that needs to be added? https://github.com/iambumblehead/esmock/blob/master/package.json#L9-L13

**Comment by iambumblehead** [comment]
@ericmorand is it possible that your setup is not using esm? I did a google search and this github issue came up in the results https://github.com/ipfs/js-ipfs/issues/4138

**Comment by iambumblehead** [comment]
**The tests must be run using esm.** Closing this issue, but feel free to re-open if necessary
