### ISSUE TITLE
Unable to mock relative TS imports [jest+ts]

### ISSUE THREAD

**Issue by cyberwombat** [iambumblehead/esmock#154]
Hi

So I'm wanting to mock an exported function from a file that is called from my code to test.

So the code to test:
````
// src/lib/utils/logUtils.ts
import { sendErrorToSentry } from './debugUtils'

export function logError(err: Error): void {
   sendErrorToSentry(error)
}
````

That code makes use of this which I want to mock:
````
// src/lib/utils/debugUtils.ts
export const sendErrorToSentry = (error: Error): void => {
  // Stuff I want to mock
  console.log('ORIGINAL)
}
````

And how I test (Jest)
````
import { jest } from '@jest/globals'
import esmock from 'esmock'

it('logError() sends errors to Sentry', async () => {
  const mockLogSentry = jest.fn()
  const mockLog = await esmock(
    '/full/path/src/lib/utils/logUtils',
    {
      '/full/path/src/lib/utils/debugUtils.js': {
        sendErrorToSentry: mockLogSentry
      }
    }
  )

  mockLog.logError(new Error())
  expect(mockLogSentry).toHaveBeenCalled()

})

````

I am using running my code in TS transpiled to ESM (so type: module) with:
````
"esmock": "^2.0.1",
"jest": "29.0.0",
"typescript": "^4.8.3"
````

And calling my test with: 
````
"node --loader=esmock --experimental-vm-modules ./node_modules/.bin/jest"
````

I've tried a few different scenarios but none of them will mock - the console always prints "ORIGINAL" and my spy never gets called. I looked at the TS example but it doesn't make use of local TS files and I wonder if that's where the issue resides.

Do you have any thoughts on this?

**Comment by iambumblehead** [comment]
I would expect this to work. jest-light-runner is required --do your tests use jest-light-runner? https://github.com/iambumblehead/esmock/wiki#calling-esmock-jest

**Comment by cyberwombat** [comment]
I did not - I thought that I needed that if I wanted to pass the loader directly to jest. At least that's how I read the docs. Are you saying even if I pass the loader to node as I do that it won't work?

**Comment by iambumblehead** [comment]
Yes, jest prevents --loader from reaching the test code. jest-light-runner somehow makes --loader work with jest.

**Comment by cyberwombat** [comment]
Ah. I remember trying to use it but it blocks any Jest setup files in TypeScript

**Comment by cyberwombat** [comment]
Actually just disabled the Jest setup - turns out it doesn't work with TS - at least not out of the box as in just adding it as a Jest runner. `  TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" ` (on my test file)

**Comment by cyberwombat** [comment]
https://github.com/nicolo-ribaudo/jest-light-runner/issues/53

From the date I assumed its abandoned.  Gah

**Comment by iambumblehead** [comment]
I'm interested to try and make this work. I hadn't considered this scenario before https://github.com/nicolo-ribaudo/jest-light-runner/issues/1

**Comment by cyberwombat** [comment]
Great! whatever I can do to help. Ive been trying to switch my TS projects to ESM for 2 years now - eventually I always give up. I'm pretty close now but the spies/mocks is the last thing. Jest has `unstable_mockModule` but that barely does anything useful.

**Comment by iambumblehead** [comment]
the tests in the linked PR use typescript (with tsm) and jest
```console
tests-jest-ts月$ npm test

> test
> run-script-os


> test:default
> NODE_OPTIONS="--loader=tsm --loader=esmock" jest esmock.node-jest.test.ts

 PASS  ./esmock.node-jest.test.ts
  ✓ should mock modules when using jest

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.398 s, estimated 1 s
Ran all test suites matching /esmock.node-jest.test.ts/i.
```

**Comment by iambumblehead** [comment]
@cyberwombat it looks like ts-node requires a tsconfig.json file https://github.com/nicolo-ribaudo/jest-light-runner/issues/1#issuecomment-1252551311 this test passes when the tsconfig.json is added

**Comment by cyberwombat** [comment]
@iambumblehead which test specifically?  I myself don't get errors with ts-node (also used `ts-node/esm/transpile-only` as a loader) but nothing gets mocked. Are you using pure Jest or with jest-light-runner?

**Comment by iambumblehead** [comment]
Changes to use ts-node/esm with jest-light-runner are pushed to the PR here https://github.com/iambumblehead/esmock/pull/155

I'm doubtful the setup files can be supported :/

**Comment by iambumblehead** [comment]
closing this ticket and feel free to re-open for any reason
