### ISSUE TITLE
Node 16.12+ breaks esmock

### ISSUE THREAD

**Issue by mroderick** [iambumblehead/esmock#16]
When upgrading to latest node, we're seeing errors with using `esmock`.

With some investigation, it looks like `16.12` is the version that broke `esmock`.

[Node 16.12 CHANGELOG](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#2021-10-20-version-16120-current-richardlau)

#### How to reproduce

0. Check out this repository
1. `nvm use 16.11`
1. `npm ci`
1. `npm test`
2. Observe tests pass
2. `nvm use 16.12`
3. `npm ci`
4. `npm test`
5. Observe many test failures

**Comment by maherma-adg** [comment]
With version esmock@1.0.0  on 16.13.0 you get this warning:
(node:13737) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getSource

**Comment by iambumblehead** [comment]
@maherma-adg do you recommend a way to resolve this? I searched for a way to conditionally export 'getSource' if node version is less than 16.12, but node forces the file to declare exports statically.

what do you think of think of this idea... two module loaders, one for node v12-v16.11 and another for node v16.13+
_node v12-v16.11_
```bash
mocha --loader=esmock/loader.getSource.mjs
```

_node v16.12+_
```bash
mocha --loader=esmock
```

I'm not exactly sure if it will work, but I think it could work.

**Comment by iambumblehead** [comment]
I would prefer if "--loader=esmock" could be used always but how does one make that load a file that only exports "getSource" for node v12-v16.11?

**Comment by iambumblehead** [comment]
@maherma-adg I found a way to make the warning go away https://github.com/iambumblehead/esmock/pull/19

**Comment by iambumblehead** [comment]
@maherma-adg try the newest version

**Comment by mroderick** [comment]
I can confirm that the issue has been resolved 👍

**Comment by maherma-adg** [comment]
It's works with ava, but I can't make it work with jest, anyone can?

**Comment by iambumblehead** [comment]
@maherma-adg I haven't tried it with jest, but doesn't jest process everything through a transpiler? Maybe that's why it doesn't work... maybe its transforming the sources into cjs or something similar

**Comment by maherma-adg** [comment]
As far as I know, jest only transpile when needed ( and you must configure transpiler ) for TS, Vue, JSX, etc.  I'll try to dig deeper.
Thanks for your useful tool.
Manuel.

**Comment by iambumblehead** [comment]
@maherma-adg https://jestjs.io/docs/ecmascript-modules try disabling transformations or configuring them to produce esm

**Comment by OlaoluwaM** [comment]
How can I set the loader?

**Comment by iambumblehead** [comment]
@OlaoluwaM if you make a PR with a sample basic jest test in it, I can try and make things work with that
