### ISSUE TITLE
reduce size of typescript types file [need help]

### ISSUE THREAD

**Issue by iambumblehead** [iambumblehead/esmock#160]
When the package is published to npm, these filesizes are listed,
```console
750B  LICENSE              
4.4kB README.md            
845B  package.json         
4.8kB src/esmock.d.ts      
824B  src/esmock.js        
129B  src/esmockArgs.js    
423B  src/esmockCache.js   
32B   src/esmockDummy.js   
125B  src/esmockIsLoader.js
1.6kB src/esmockLoader.js  
2.2kB src/esmockModule.js
```

Total size from all files is 16.1kB and 4.4kB is 27% of 16.1kB. The types file has multiple repeated sections in it.

**Comment by iambumblehead** [comment]
related https://github.com/iambumblehead/esmock/pull/163

**Comment by iambumblehead** [comment]
related https://github.com/iambumblehead/esmock/pull/164

**Comment by jsejcksn** [comment]
This is not something to be concerned about. Types are only used during development (pre-compilation) and are not included in production builds/bundles, so they'll have no effect on terminal consumer bandwidth.
