### ISSUE TITLE
`MockFunction` return type may be generic

### ISSUE THREAD

**Issue by cawa-93** [iambumblehead/esmock#169]
https://github.com/iambumblehead/esmock/blob/28cbda5dfa97d73757d6c37d53a74f14d1b9156b/src/esmock.d.ts#L9

It allows you type mocked module like so:
```ts
const myModule = await esmock<typeof import('/module/path')>('/module/path')

**Comment by cawa-93** [comment]
cc:  @jsejcksn

**Comment by iambumblehead** [comment]
is the issue that, the new typescript types file is forcing you to define `<typeof import('/module/path')>`? should we revert the esmock.d.ts?

**Comment by cawa-93** [comment]
No. It's enhansment. Currently `esmock('module/path')` return `any` and user will not get code intellisense. Type resolution from module may be automated if https://github.com/microsoft/TypeScript/issues/31090 will be resolved.

Actually, I just realise, that user can set type just like: 🤦🏻‍♂️

```ts
const myModule: typeof import('/module/path') = await esmock('/module/path')
```

So, I close this as no actual, until https://github.com/microsoft/TypeScript/issues/31090 was resolved

**Comment by iambumblehead** [comment]
@cawa-93 thanks for sharing that is great
