### ISSUE TITLE
Error: invalid moduleId when trying to stub a module dependency ES6

### ISSUE THREAD

**Issue by umakanth-pendyala** [iambumblehead/esmock#174]
I have created 2 files add.js and server.js. The files are as follows

add.js

```
const add = () => {
    return 10
}

export { add }
```
server.js

```
import { add } from './add.js'

function print() {
    console.log(add())
}

export {print}
```
I have written a unit test file for server.js as follows

```
import { expect } from 'chai'
import esmock from 'esmock'
import sinon from 'sinon'

describe('server.js', () => {
    const addStub = sinon.stub()
    const m = esmock('../server.js', {
        ['./add.js']: {
            add: addStub
        }
    })

    it ('should work', () => {
        console.log(m)
        m.print()
        expect(2).be.equal(2)
    })
})
```
I have used a library called esmock which works similarly to proxyquire. But when I ran the test using mocha. I got the following error

` Error: invalid moduleId: "./add.js"`
I am wondering what could be the issue here. Is the problem related to the path specified in esmock or the way I am acquiring the import?

FYI: esmock with same syntax works well for standard imports from npm like axios or aws-sdk

I was hoping someone could help me figure out whats the problem. Thanks in advance!

**Comment by iambumblehead** [comment]
@umakanth-pendyala try this. Also, ff server.js and add.js are in the same directory, define the mock definition on "../add.js" (same location as "../server.js"),
```diff
    const m = esmock('../server.js', {
-        ['./add.js']: {
+        '../add.js': {
            add: addStub
        }
    })
```

**Comment by umakanth-pendyala** [comment]
Tried that, no luck.

**Comment by iambumblehead** [comment]
Awesome. When that error is thrown, the [full path is shortened.](https://github.com/iambumblehead/esmock/blob/master/src/esmockErr.js) If the error showed the full path, it would have been easier to see the path wasn't right.

Maybe the full path should be printed.

**Comment by iambumblehead** [comment]
Thanks for using esmock and for opening this issue
