### ISSUE TITLE
What about Yarn PnP support?

### ISSUE THREAD

**Issue by koshic** [iambumblehead/esmock#176]
Any loader used in PnP mode can't resolve/load any packages except Node builtins. Yep, we have discussion in Node community how to improve loaders, how to redesign API, etc.

But now only one way - to have bundled loader. It works perfectly for me (I use simple esdbuild-based transpiler for .ts, as an example), but I can't use esmock 'out of box' (proxy bundle is the way, but...) to try node native test runner instead of Jest. 

Can we remove single external dependency, 'resolvewithplus' here? Or, mark it optional and use import.meta.resolve (by flag / different import path like esmock/native or so on).

**Comment by iambumblehead** [comment]
@koshic does resolvewithplus need to be removed from package.json? If resolvewithplus is not removed from package.json, but if esmock does something like this, would this work for your situation?
```javascript
const resolver = typeof import.meta.resolve === 'function'
  ? import.meta.resolve
  : (await import('resolvewithplus')).default
```

**Comment by koshic** [comment]
@jakebailey I think the second one is the best solution, with marking resolvewithplus as optional peer dependency, thx!

**Comment by iambumblehead** [comment]
there will be less maintenance, if we wait for import.meta.resolve to be stable and complete before using it.

**Comment by iambumblehead** [comment]
> Or, mark it optional and use import.meta.resolve (by flag / different import path like esmock/native or so on).

a good idea BUT esmock tried exporting something like this a month or two ago and typescript does not support this sort of thing https://github.com/TypeStrong/ts-node/discussions/1877 even if typescript could (or can?) do this, the support is or will not be great and annoying complexity necessary to placate typescript

**Comment by koshic** [comment]
> "import.meta.resolve" does [not resolve subpaths.](https://github.com/iambumblehead/esmock/pull/179) [The test](https://github.com/iambumblehead/esmock/blob/master/tests/tests-node/esmock.node.test.js#L32-L42) creates a call like `await import.meta.resolve('#sub', parent)`
> 
It supports:
<img width="1683" alt="image" src="https://user-images.githubusercontent.com/20106607/196408516-8c224a93-9f37-453b-8930-4678b43d5ae1.png">

**Comment by koshic** [comment]
> there will be less maintenance, if we wait for import.meta.resolve to be stable and complete before using it.

--experimantal-loaders is experimental too, so waiting can be looong )

**Comment by iambumblehead** [comment]
@koshic if you approve [this PR,][0] let's merge and use follow-up PRs to specifically resolve the two issues,
 1. https://github.com/iambumblehead/esmock/issues/178 use loader mechanism directly to detect esmock loader,
 2. https://github.com/iambumblehead/esmock/issues/176 (this ticket) make resolvewithplus an optional dependency

I have not used optional dependencies myself so am interested to see how it works. If resolvewithplus is an optional dependency, will npm continue to download it by default for esmock? My research indicates resolvewithplus will continue to be downloaded in the default case, but I haven't used optional dependencies before so am not certain.

@koshic if you still have test files you made for testing stub export, would you test if import.meta.resolve returns paths for moduleIds with extensions like "tsx" or "json"? If you're not interested to test this that's good and I can make a little test later this evening or tomorrow.

[0]: https://github.com/iambumblehead/esmock/pull/179

**Comment by koshic** [comment]
@iambumblehead I will approve after few small fixes )

And yes, import.meta.resolve returns all paths:
<img width="1693" alt="image" src="https://user-images.githubusercontent.com/20106607/196682377-fa32eb0e-8280-45f3-b6d6-58c1008cd453.png">

**Comment by iambumblehead** [comment]
changes are published and deployed https://github.com/iambumblehead/esmock/releases/tag/v2.0.7

feel free to re-open if there is any issue :)
