### ISSUE TITLE
Minified sources in esmock package

### ISSUE THREAD

**Issue by koshic** [iambumblehead/esmock#177]
It's not a feature request (yet), but only question - why?

From my understanding, JS ecosystem provides the greatest debugging ability - everything is script, and you can easily inspect / modify installed packages without IDA. And browser-like minification totally breaks it.

Package download size? No - packages published as archives with good text compression out of the box.
Package disk usage? May be, but cute readme with ascii art already takes 4k ) 

Performance? Perhaps, but in the most real-world scenarios it's only premature optimization (which is may be much more evil than real performance problems, you know). Especially for small, one-time loaded scripts like Node loaders. 

<img width="950" alt="image" src="https://user-images.githubusercontent.com/20106607/196313445-72a004c2-355a-4041-831a-5c010353f3b2.png">

Fortunately, I can just copy source code directly from github )

**Comment by iambumblehead** [comment]
Mostly, I think its cool to have a really small package size --inspired by these packages emphasizing smallness,
 * https://github.com/ai/nanoid
 * https://github.com/nanostores/nanostores
 * https://github.com/usmanyunusov/nano-staged
 * https://github.com/lukeed/uvu/


> Fortunately, I can just copy source code directly from github )

That's the [recommended way.](https://github.com/iambumblehead/esmock/issues/71#issuecomment-1231747807) I don't believe many people need to do debug esmock and am confident in esmock so enjoy the smaller package size that comes with minification.

The README uses big ascii art, but is still smaller than READMEs used by similar packages :)

**Comment by koshic** [comment]
If you don't believe that people will be changing something in node_modules / .yarn/unplugged, why do you place readme inside tarball? )

**Comment by iambumblehead** [comment]
* npm automatically includes README in the package,
 * the README is needed to show something to people visiting the npm page https://www.npmjs.com/package/esmock
 * the inspiration packages listed above come with READMEs
 * the README and even the ascii art are important

**Comment by iambumblehead** [comment]
closing this, feel free to re-open or discuss as you may prefer
