### ISSUE TITLE
Invalid check in esmockIsLoader.js

### ISSUE THREAD

**Issue by koshic** [iambumblehead/esmock#178]
https://github.com/iambumblehead/esmock/blob/5dfe486f8837c25d9651a0f269abfa454c3e342e/src/esmockIsLoader.js#L1

What if esmock loaded indirectly, as part of other loader?

<img width="410" alt="image" src="https://user-images.githubusercontent.com/20106607/196315360-71b0af44-5d16-4ff6-bb4d-51b2c23293ce.png">

`Error: process must be started with --loader=esmock`

I suggest to set flag in global object inside resolve / load, or something like that.

**Comment by iambumblehead** [comment]
Loader's will use separate thread wout access to that global object https://github.com/nodejs/node/pull/44710

Would something like this work for indirect loading? What do you think?
```javascript
import esmock from 'esmock'

esmock.isLoaderRequired = false

esmock(...args)
```

**Comment by iambumblehead** [comment]
another way might be to support a call like this, where the options param defines "isLoaderRequired" as false,
```javascript
esmock('./module.js', defs, globaldefs, {
  isLoaderRequired: false
})
```

**Comment by koshic** [comment]
What is the reason to check? For my understanding, it was created to avoid setup mistakes (for users) and to make predictable environment (for author).

So, this check in not about particular Node parameters / esmock, it's about esmock resolve/load hooks (both!) are loaded by Node engine. 

How to achieve that? I see 2 obvious options:
1) Composite flag like 'isLoadHookInstalled/ usResolveHookInstalled', each part can be set at the first call on the hooks. It can't provide 100% guarantee due to prev load in chain can serve all requests by its own and never call 'nextLoad / nextResolve'.
2) import 'esmock.ebabled' in runtime- which is require special handling in resolve (ok, it's a module) and load (return {source: 'true'})

Personally, I prefer option 2 because it guarantee that we have 2 hooks and they know about esmock. Can it be a fake? Sure. Can it happen by mistake? No.

**Comment by koshic** [comment]
I mean that esmockIsLoader() implementation is a bit naive, and relates on way how to loader added to Node loaders chain. And my proposal is to use direct interaction with 'black box' (Node + any number of loaders), by use the following code in esmockIsLoader:
```
try {
  const xxx = await import('any-non-existent-specifier, like flags.esmock ot enabled.esmock')
  return true;
} catch {
  return false;
}
```

If esmock hooks were loaded, they will handle this request and return something to 'xxx' variable (just for example).
If there is no esmock hooks, import() will fail. 

100% guaranteed, right?

**Comment by iambumblehead** [comment]
@koshic an interesting and clever idea :) yes I like that

**Comment by koshic** [comment]
> @koshic an interesting and clever idea :) yes I like that

Yep, it's an unblockable pipe between loaders & 'user space'.

**Comment by iambumblehead** [comment]
changes are published and deployed https://github.com/iambumblehead/esmock/releases/tag/v2.0.7
