### ISSUE TITLE
Issues with pnpm

### ISSUE THREAD

**Issue by PatrickHeneise** [iambumblehead/esmock#187]
This works fine when modules are installed with `npm`, but with `pnpm` the module id doesn't seem to match and the module code is executed. When using `strictest`, it complains about the module id not found.

### code

```js
'use strict'

import { SecretManagerServiceClient } from '@google-cloud/secret-manager'
const client = new SecretManagerServiceClient()

export async function fetchVariable(projectId, key) {
  const [accessResponse] = await client.accessSecretVersion({
    name: 'projects/${projectId}/secrets/${key}/versions/latest'
    }`
  })

  return [key, accessResponse.payload.data.toString('utf8')]
}

```

### test

```js
'use strict'

import { test } from 'tap'
import esmock from 'esmock'

test('fetchVariable() returns value', async ({ equal }) => {
  const { fetchVariable } = await esmock('../lib/fetchVariable.js', {
    '@google-cloud/secret-manager': {
      SecretManagerServiceClient: (() =>
        class {
          async accessSecretVersion(name) {
            return Promise.resolve([
              {
                payload: {
                  data: Buffer.from(name.name)
                }
              }
            ])
          }
        })()
    }
  })
  const [key, value] = await fetchVariable('project', 'testkey')
  equal(key, 'testkey')
  equal(value, 'projects/project/secrets/testkey/versions/latest')
})
```

**Comment by iambumblehead** [comment]
Related PnP-compatibility changes were made for this issue https://github.com/iambumblehead/esmock/issues/176

@koshic do you know of a solution for using esmock with PnP? It seems to still not be working. @koshic @PatrickHeneise esmock could be updated with changes you might recommend for resolving this issue

**Comment by koshic** [comment]
@iambumblehead pnpm and yarn PnP are very different things )

I can answer about PnP only:
1. yarn unplug esmock to place it somewhere inside .yarn/unplugged dir
2. yarn node --loader $(yarn node --input-type=module -e 'console.log((await import("module")).default.findPnpApi(".").resolveRequest("esmock", `${process.cwd()}/dummy.js`, { conditions: new Set(["import"]) }))')

Sure, we can create simple wrapper for second step - do the same to get esmock path, dynamically import esmock and export load + resolve hooks (my reason why I requested changes in 'is esmock loaded?' fn).

**Comment by iambumblehead** [comment]
@koshic ah I see pnpm is a different thing!

@PatrickHeneise which moduleId is not found? Would you share the full message? If you use esmock with `--experimental-import-meta-resolve` do your tests run correctly?

**Comment by iambumblehead** [comment]
@PatrickHeneise would you also try calling esmock and using the full path the the module for which the moduleId is not found? Iow, if '@google-cloud/secret-manager' is the moduleId that s not found, try something like this,
```diff
  const { fetchVariable } = await esmock('../lib/fetchVariable.js', {
-    '@google-cloud/secret-manager': {
+    '/full/path/to/node_modules/@google-cloud/secret-manager': {
       // ...
    }
  })
```

**Comment by iambumblehead** [comment]
@PatrickHeneise also feel free to submit a failing test and I will merge and try to resolve per https://github.com/iambumblehead/esmock/blob/master/CONTRIBUTING.md

**Comment by PatrickHeneise** [comment]
Thanks for the support! I'll try to run it later or tomorrow again with experimental mode and the full path, see what works.

**Comment by PatrickHeneise** [comment]
_tomorrow_ ... closing this as I don't have capacity at the moment. Will run the test when I get back to this project. Thanks though!

**Comment by iambumblehead** [comment]
@PatrickHeneise thanks and regards hoping everything is good for you this holiday season. Feel free to re-open or message any time
