### ISSUE TITLE
strictest silently allows to pass {} or undefined as defs -> real dependencies are used

### ISSUE THREAD

**Issue by koshic** [iambumblehead/esmock#192]
Looks like it's a normal behaviour for regular mode (and may be for strict), but my expectations is 'you MUST provide full defs object to get this work, tested module can't work with empty defs". Sure, it's only my expectations, but I propose to change docs and reflect that 'empty defs > no mocking', or throw runtime exception. Thx!

https://github.com/iambumblehead/esmock/pull/191

**Comment by iambumblehead** [comment]
thanks for opening the issue. I'm very busy at this moment and do not know when I will be available to respond effectively.
