### ISSUE TITLE
not working in node 12.x (windows-latest)?

### ISSUE THREAD

**Issue by aladdin-add** [iambumblehead/esmock#20]
does the package support node 12.x(windows-latest)?
I just got an error like `Error: modulePath not found: "../../lib/init/config-file.js"`. the weird thing is it's working fine in non-windows.

the job log: https://github.com/eslint/create-config/runs/4307659622?check_suite_focus=true

**Comment by iambumblehead** [comment]
@aladdin-add the link returns a 404 page for me however I'm interested to reproduce and resolve the issue.

Maybe its possible to setup a windows node 12.x ci pipeline to catch this.

**Comment by aladdin-add** [comment]
oh, sorry! didn't notice it's a private repo. will make a repro later.

**Comment by aladdin-add** [comment]
https://github.com/aladdin-add/eslint-create-config/runs/4307915361?check_suite_focus=true

**Comment by iambumblehead** [comment]
this windows-latest pipeline shows the failure https://github.com/iambumblehead/esmock/runs/4308082925?check_suite_focus=true

Unfortunately I don't have a windows machine but I'll message my friend who has one.

**Comment by aladdin-add** [comment]
might be related to windows-style paths, e.g. `\node\module.js`?

**Comment by iambumblehead** [comment]
@aladdin-add a little update here. I'm reproducing this using a virtual machine windows on mac.

<img width="1136" alt="Screen Shot 2021-11-25 at 12 05 12 PM" src="https://user-images.githubusercontent.com/2058705/143495809-708642cc-de45-4a33-9109-ec0e7102e68d.png">

**Comment by iambumblehead** [comment]
@aladdin-add this issue relates to a specific requirement node has for paths returned by the module loader on Windows: those paths must begin with "file://" whereas other systems do not need this,
```javascript
  Error {
    code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME',
    message: 'Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol \'d:\'',
  }
```
solving this part will probably get the tests to pass but I'm not sure if I'll get around to it today

**Comment by iambumblehead** [comment]
all tests are passing here https://github.com/iambumblehead/esmock/pull/21

**Comment by aladdin-add** [comment]
I've confirmed it was fixed in our repo. excellent job, thanks!! 💯

**Comment by iambumblehead** [comment]
@aladdin-add thank you

**Comment by iambumblehead** [comment]
closing as resolved
