### ISSUE TITLE
Node 20.x: import.meta.resolve is not a promise anymore

### ISSUE THREAD

**Issue by koshic** [iambumblehead/esmock#200]
https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#2023-04-18-version-2000-current-rafaelgss
https://github.com/nodejs/node/pull/44710

As a result, https://github.com/iambumblehead/esmock/blob/4425101785857d1ba09012694dd96e64bb593322/src/esmockModule.js#L120 fails with 'TypeError: (intermediate value).resolve(...).catch is not a function'.

**Comment by iambumblehead** [comment]
I might have time to make a branch and resolve later tonight or tomorrow. Thanks for bumping the node --loader issue thread I hope they will resolve that
