### ISSUE TITLE
Unexpected token 'delete'

### ISSUE THREAD

**Issue by mcbalomirean** [iambumblehead/esmock#203]
I have a dependency I'm trying to mock which contains a `delete` function. Something like:

```js
await esmock('./path/to/module.js', {
    './path/to/dependency.js': { delete: () => {} }
})
```

When I run the tests, I get the error in the title.

```
SyntaxError[ @/path ]: Unexpected token 'delete'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:475:14)
```

Unfortunately, the dependency is not my own module (it is an external package) so I can't change the name of the function. Is there a chance this could be fixed, or is there a workaround? Thank you!

**Comment by Swivelgames** [comment]
Have you tried wrapping the property name? I'm not entirely sure if this is specifically an issue with `esmock`, and more so JavaScript not liking the fact that you're trying to use a keyword when its expecting to see an object member identifier.

Try this instead:

```javascript
await esmock('./path/to/module.js', {
    './path/to/dependency.js': { 'delete': () => {} }
})
```

**Comment by iambumblehead** [comment]
@mcbalomirean if you could possibly make a small reproduction demonstration, that would be really great an helpful

**Comment by iambumblehead** [comment]
could try to make a reproduction myself later but might need to do so on Friday or Saturday (busy today)

**Comment by mcbalomirean** [comment]
Sure, here's a .zip with a small project. Error should repro when you run `test`.
[esmock-unexpected-token-delete.zip](https://github.com/iambumblehead/esmock/files/11500864/esmock-unexpected-token-delete.zip)

**Comment by iambumblehead** [comment]
@mcbalomirean thanks that's a terrific reproduction

**Comment by iambumblehead** [comment]
@mcbalomirean looking at the test package you uploaded... the mock definition there is not correct. The original file "some_module.js" exports the name "content" and does not export "delete". Try mocking "content" using changes in this diff
```diff
import esmock from "esmock";

await esmock("../src/to_test.js", {
  "../src/some_module.js": {
+  content: {
    delete: () => {
      console.log("Oh no, I've been mocked.");
    },
+  }
  },
});
```

**Comment by iambumblehead** [comment]
exporting "delete" is disallowed by node. closing this issue but if there is a misunderstanding or some reason to reopen feel free to reopen
```bash
$ echo "export const delete = 1" >> test.mjs && node test.mjs
file:///home/bumble/test.mjs:1
export const delete = 1
             ^^^^^^

SyntaxError: Unexpected token 'delete'
    at DefaultModuleLoader.moduleStrategy (node:internal/modules/esm/translators:116:18)
    at DefaultModuleLoader.moduleProvider (node:internal/modules/esm/loader:206:14)
    at async link (node:internal/modules/esm/module_job:67:21)

Node.js v20.2.0
```

**Comment by mcbalomirean** [comment]
Thank you for looking at this, After looking at your replies, I managed to work around the issue by doing the following:

```js
import esmock from "esmock";

await esmock("../src/to_test.js", {
  "../src/some_module.js": {
    default: {
      delete: () => {
        console.log("Oh no, I've been mocked.");
      },
    },
  },
});
```

The original code exported an object which had the `delete` method in it, and when mocked (by giving ESMock an object with a `delete` method as the mock) it would be interpreted as if it were exported separately, i.e. `export const delete` as you mentioned. What I was expecting was that the object I'm passing as the mock be interpreted as the _default_ export, which was a misunderstanding I had.

I hope this helps anyone encountering this problem in the future.
