### ISSUE TITLE
Mock a package globally

### ISSUE THREAD

**Issue by afshin-hoseini** [iambumblehead/esmock#204]
I got a bunch of test modules that are dependent on a 3rd party module (package), let's say `axios` or an encryption package.
Is it possible to mock the package once or should I esmock on each test module separately?

like:
```
await esmock('axios', {request: ()=>...});
```

And whatever module invokes `axios.request`, would actually run the stubbed version.

**Comment by iambumblehead** [comment]
@afshin-hoseini use the third param to define global mocks,
```javascript
await esmock('./path/to/module.js', {}, {
  'axios', { request: () => 'returns this globally' }
})
```
