### ISSUE TITLE
Mock dependency

### ISSUE THREAD

**Issue by yumauri** [iambumblehead/esmock#212]
Maybe duplicate of #204, but answer there is not enough, or I just too dumb to understand it :(

I have a package with library, which is like "addon" for another library. It cannot be used without this 3rd party library. It uses this library internally, and expects that users are using this library as well.

I want to test functionality with different versions of 3rd party library.

I have different versions installed via dependencies aliases, like

```json
"library_v1": "npm:library@1.0.0",
"library_v2": "npm:library@2.0.0",
```

And I want to run same tests with one version of a library and then with another version. This should affect both, AND source code, which I test, AND tests as well (because they use this library like user-space code).

For now I use [`rewiremock`](https://github.com/theKashey/rewiremock) with [configuration file](https://github.com/yumauri/effector-storage/blob/main/tests/rewiremock.ts), which replaces library depending on defined environment variable. But looks like this package is not very actively supported, so I'm looking for alternatives.

Is it possible to do the same with `esmock`?

**Comment by iambumblehead** [comment]
I'm not too familiar with this scenario. esmock essentially looks up module paths using logic per import.meta.resolve https://nodejs.org/api/esm.html#importmetaresolvespecifier-parent and applies the specified mock to the definition loaded at the path.

@yumauri in your opinion, how would _should_ esmock support the situation you describe?

**Comment by iambumblehead** [comment]
@yumauri what do you think of something like this?
```javascript
import test from 'node:test'
import assert from 'node:assert/strict'
import esmock from 'esmock'
import depvsn1 from '../path/to/dep-vsn1.0.0'
import depvsn2 from '../path/to/dep-vsn2.0.0'

test('my-script with dep version 1', async () => {
  const scriptUsingDepVsn1 = await esmock('../my-script.js', {}, {
    dep: depvsn1
  })

  assert.ok(scriptUsingDepVsn1.usingDependencySucceeds())
})

test('my-script with dep version 2', async () => {
  const scriptUsingDepVsn2 = await esmock('../my-script.js', {}, {
    dep: depvsn2
  })

  assert.ok(scriptUsingDepVsn2.usingDependencySucceeds())  
})
```

**Comment by iambumblehead** [comment]
There may well be a simpler way to do this I'm unaware of. I'm just not familiar with this situation where a file uses different version of the same dependency

**Comment by iambumblehead** [comment]
@yumauri _another idea_ if it is reasonable to do so, the add-on package being testing could use separated test-suites for each version of the dependency that is used. esmock, for example, uses different test runner and typescript loader combinations and uses separated test suites for those https://github.com/iambumblehead/esmock/tree/master/tests

**Comment by yumauri** [comment]
Thing is I want to run same tests. For now I have 34 test suites with 171 tests in total. I would not like to double them all, this sounds like nightmare.

Unfortunately, I'm not familiar with module resolution in Node, and how `rewiremock` doing it... So I'm not sure about how API should look like. Maybe some way to globally intercept into module resolution process. This is how it looks like with `rewirework`, at least.

```js
// esmock.mjs
import esmock from 'esmock'
import library_v1 from 'library_v1'
import library_v2 from 'library_v2'

const useVersion = process.env.USE_LIBRARY_VERSION || 'v1'
const library = useVersion === 'v1' ? library_v1 : library_v2

export default esmock.resolve('library').with(library)
```

and then use this file as loader
```
NODE_OPTIONS=--loader=./esmock.mjs ...
```

Other possible solution for my task — is to actually reinstall library to other version each time before running tests. And do not mock it at all. This sounds not too appealing as well, but I'm thinking about it too.

**Comment by yumauri** [comment]
> I'm just not familiar with this situation where a file uses different version of the same dependency

This is called back compatibility :) I want to be sure, that my library works as intended with different versions of 3rd party library. At least with two latest major versions.

**Comment by iambumblehead** [comment]
@yumauri thank you that is an interesting and clear example given there. esmock does not support that sort of scenario now but your example shows how it could be useful. 

Possibly quibble is a better mocking package for your use-case https://github.com/testdouble/quibble

Currently, one would need to need to generate a new import tree for each test to include the dependency version needed by the test.
```javascript
import test from 'node:test'
import assert from 'node:assert/strict'
import esmock from 'esmock'
import libraryV1 from '../path/to/library-vsn1.0.0.js'
import libraryV2 from '../path/to/library-vsn2.0.0.js'

const myScriptWithLibVersion = async () => esmock('../my-script.js', {}, {
  dep: process.env.USE_LIBRARY_VERSION === 'v1'
    ? libraryV1
    : libraryV2
})

test('my-script behaviour A', async () => {
  const myScript = await myScriptWithLibVersion()

  assert.ok(myScript.behaviourASucceeds())
})

test('my-script behaviour B', async () => {
  const myScript = await myScriptWithLibVersion()

  assert.ok(myScript.behaviourBSucceeds())
})
```

if statefulness of the dependency does not present a problem, the same import tree could be returned to all callers eg something like this
```javascript
import test from 'node:test'
import assert from 'node:assert/strict'
import esmock from 'esmock'
import libraryV1 from '../path/to/library-vsn1.0.0.js'
import libraryV2 from '../path/to/library-vsn2.0.0.js'

const myScriptWithLibVersion = async () => esmock('../my-script.js', {}, {
  dep: process.env.USE_LIBRARY_VERSION === 'v1'
    ? libraryV1
    : libraryV2
})

const myScriptWithLibVersionCached = (c => async () =>
  c || (c = myScriptWithLibVersion()))()

test('my-script behaviour A', async () => {
  const myScript = await myScriptWithLibVersionCached()

  assert.ok(myScript.behaviourASucceeds())
})

test('my-script behaviour B', async () => {
  const myScript = await myScriptWithLibVersionCached()

  assert.ok(myScript.behaviourBSucceeds())
})
```

There may be other ways to optimise and simplify. ava and node:test both support this 'beforeEach' call which could be included in your test formula
```javascript
const globalImports = {}

test.beforeEach(async () => {
  globalImports.myScript = await myScriptWithLibVersion()
})
```

**Comment by yumauri** [comment]
Ok, I got it, thank you for explanations.
I'll look at `quibble` as well, not sure I saw it before.
