### ISSUE TITLE
Is it possible to mock a binary's imports?

### ISSUE THREAD

**Issue by tommy-mitchell** [iambumblehead/esmock#214]
I'm writing a CLI and I've separated some helpers with side-effects into another file and have unit tested those. It would be much easier to test the CLI if I can stub the helpers and disregard the side-effects.

Is it possible to mock the imports of a CLI / child process? Such as (pseudocode):

```js
await esmock("../src/cli.js", {
	"./helpers.js": {
		foo: someSpyOrStub(),
		bar: someSpyOrStub(),
	},
});
```

Or maybe with `execa`:

```js
const spy = // ...
const cli = await esmock("../src/cli.js", { /* ... */ });

const { exitCode } = await execa(cli);

t.is(exitCode, 0);
t.true(spy.called);
```

If I try running the first code snippet, the CLI is invoked without any mocks being applied.

**Comment by tommy-mitchell** [comment]
Seems like it's possible using [`testdouble`](https://github.com/testdouble/testdouble.js/blob/main/docs/7-replacing-dependencies.md#how-module-replacement-works-for-es-modules-using-import) / [`quibble`](https://github.com/testdouble/quibble#es-modules-support):

```js
// src/helpers.js
export const foo = () => "foo";
```

```js
// src/cli.js
import { foo } from "./helpers.js";

console.log(foo());
//=> expected: "foo"
```

```js
// test.js
import * as td from "test-double";

await td.replaceEsm("./src/helpers.js", { foo: () => "bar" });

await import("./src/cli.js");
//=> actual: "bar"
```

**Comment by koshic** [comment]
@tommy-mitchell may be I missed something, but why you can't use globalmocks from
```js
await esmock(
  './to/module.js', // filepath to the source module being tested
  import.meta.url, // parentUrl from which mocked modules should be resolved
  { ...childmocks }, // mock definitions imported by the source module, directly
  { ...globalmocks }) // mock definitions imported anywhere in the source import tree
```

**Comment by iambumblehead** [comment]
> If I try running the first code snippet, the CLI is invoked without any mocks being applied.

Maybe the path should be "../src/helpers.js"?
```javascript
await esmock("../src/cli.js", {
	"../src/helpers.js": {
		foo: someSpyOrStub(),
		bar: someSpyOrStub(),
	},
});
```
esmock should throw an error if no module is found at the "helpers.js" path. We can only guess about the layout and naming of your files

**Comment by iambumblehead** [comment]
though I don't know what your cli file looks like and maybe the idea is not helpful, perhaps the cli file could be made into a basic wrapper file that imports and calls more typical javascript file. The typical javascript file could be mocked more easily as a target for unit-tests eg,

_app.cli.js_
```javascript
#! /usr/bin/env node
import app from './app.mjs';

(async () => {
  try {
    const res = await app( process.env );

    console.log('[...] cli success!:', JSON.stringify(res, null, '  '));
  } catch (e) {
    console.error(`Error!!: ${e.message}`);

    throw new Error('cli failed!');
  }
})();
```
Using a cli file like this one, the regular "app" could be unit-tested in a typical sort of way where env vars would become params the app is called with

**Comment by iambumblehead** [comment]
@tommy-mitchell I could be misunderstanding something but agree with @koshic that this form should work for your case
```javascript
await esmock("../src/cli.js", {
  "../src/helpers.js": {
    foo: someSpyOrStub(),
    bar: someSpyOrStub()
  }
});
```

**Comment by tommy-mitchell** [comment]
My issue was an incorrect module specifier and some confusion about how a module gets invoked. Besides the issue in #215, this is working as intended.
