### ISSUE TITLE
Mocking a file with a hashbang using the `import` key fails

### ISSUE THREAD

**Issue by tommy-mitchell** [iambumblehead/esmock#215]
Given some file `cli.js`:

```js
#!/usr/bin/env node
import someConstant from "./foo.js";

console.log(someConstant);
```

Trying to mock this with the `import` key fails with the error

```
file:///.../cli.js?esmk=1:1
import {console} from 'file:///import?esmkTreeId=1&esmkModuleId=import&isfound=false&isesm=false&exportNames=console';#!/usr/bin/env node
                                                                                                                      ^

SyntaxError: Invalid or unexpected token
	at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
	at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
	at async link (node:internal/modules/esm/module_job:68:21)
```

`esmock` call:

```js
const logs = [];

await esmock("./cli.js", {
	"./foo.js": "bar",
	import: {
		console: { log: (...args) => logs.push(...args) },
	},
});
```

**Comment by tommy-mitchell** [comment]
I think the issue is that hashbangs [have to be at the start of the file (MDN)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#hashbang_comments):

> A hashbang comment ... is only valid at the absolute start of a script or module. Note also that no whitespace of any kind is permitted before the `#!`. The comment consists of all the characters after `#!` up to the end of the first line; only one such comment is permitted.

`esmock` is inserting `import` globals before the hashbang.

**Comment by koshic** [comment]
Very similar issue without hashbang.

foo.js
```js
export default 1;
```
cli.js
```js
import someConstant from "./foo.js";

console.log(someConstant);
```
1.js
```js
import esmock from "esmock";

await esmock("./cli.js", {
  "./foo.js": "bar",
});
```

```
file:///Users/xxxfoo.js?esmkTreeId=1&esmkModuleId=./foo.js&isfound=true&isesm=false&exportNames=0,1,2,default:1
export const 0 = global.esmockCacheGet("file:///Users/xxx/foo.js?esmkTreeId=1&esmkModuleId=./foo.js&isfound=true&isesm=false&exportNames=0,1,2,default").0
             ^

SyntaxError: Unexpected number
    at CustomizedModuleLoader.moduleStrategy (node:internal/modules/esm/translators:116:18)
    at CustomizedModuleLoader.moduleProvider (node:internal/modules/esm/loader:190:14)
```

**Comment by iambumblehead** [comment]
> esmock is inserting import globals before the hashbang.

I think you are correct :) thanks for finding this. I should have time this evening or tomorrow to look at PRs or try to resolve it myself

**Comment by iambumblehead** [comment]
<img width="420px" alt="Screen Shot 2023-07-27 at 8 43 19 PM" src="https://github.com/iambumblehead/esmock/assets/2058705/aac9624a-a312-414b-8a23-94f77eceb121">

I don't know why the win32 error is occurring. The error indicates that paths like "node:fs" are only available in esm to packages using "type": "module", but the error originates inside an esm "load" hook and tests are started inside the tests-source-map folder which includes a package.json with "type": "module"

I don't know what causes the issue

**Comment by iambumblehead** [comment]
related https://github.com/nodejs/node/issues/35518

**Comment by iambumblehead** [comment]
The ci error went away when node 18.16 was pinned. The error occurs on the latest 18.17

A new ticket is created at the node repo here let's see what they say https://github.com/nodejs/node/issues/48948

**Comment by iambumblehead** [comment]
closing with this https://github.com/iambumblehead/esmock/pull/217

feel free to reopen for any reason
