### ISSUE TITLE
Error when using `import` key with modules that have CJS imports

### ISSUE THREAD

**Issue by tommy-mitchell** [iambumblehead/esmock#218]
Repro: https://github.com/tommy-mitchell/esmock-repro-cjs

If a module has a CJS dependency, mocking globally with the `import` key causes an error:

```
file:///.../node_modules/camelcase-keys/index.js?esmkgdefs=file:///import?esmkTreeId=1&esmkModuleId=import&isfound=false&isesm=false&exportNames=console:1
import {console} from 'file:///import?esmkTreeId=1&esmkModuleId=import&isfound=false&isesm=false&exportNames=console';import mapObject from 'map-obj';
                                                                                                                             ^^^^^^^^^
SyntaxError: The requested module 'map-obj' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

I can create a PR with a failing test.

**Comment by iambumblehead** [comment]
thanks for finding this I should have bandwidth later today work with the PR

**Comment by tommy-mitchell** [comment]
@iambumblehead I'm still getting this error, but I can't reproduce it in my minimal example (https://github.com/tommy-mitchell/esmock-repro-cjs). Will update when I can.

**Comment by tommy-mitchell** [comment]
@iambumblehead it only reproduces when using TypeScript / `ts-node`: https://github.com/tommy-mitchell/esmock-repro-cjs/tree/typescript

**Comment by iambumblehead** [comment]
@tommy-mitchell thanks I see the issue and have a solution

**Comment by iambumblehead** [comment]
https://github.com/iambumblehead/esmock/pull/224 context.format is not always defined and nextLoad().format is always defined and using nextLoad().format allows the test to pass

**Comment by iambumblehead** [comment]
the test fails with the master esmock sources but passes with the changes here

**Comment by iambumblehead** [comment]
closed with https://github.com/iambumblehead/esmock/pull/224 feel free to reopen

**Comment by iambumblehead** [comment]
changes are published to the latest version on npm https://www.npmjs.com/package/esmock
