### ISSUE TITLE
Support Yarn PnP resolver out of the box

### ISSUE THREAD

**Issue by koshic** [iambumblehead/esmock#253]
Due to default resolver (resolvewithplus) doesn't support PnP, users can use custom resolvers to work in PnP environment - https://github.com/iambumblehead/esmock/wiki#call-esmock-yarn-pnp. It's a small effort for one test, but what if existing project contains 1000+ tests? 

We can implement PnP detection in esmock, and use our own PnP resolver instead of resolvewithplus (esmockArgs.js):
```js
import resolvewithplus from 'resolvewithplus'

const resolver = process.versions.pnp === undefined ? resolvewithplus : (await import("./pnp-resolver.js")).default

arg[4] = { resolver, ...arg[4], ...optsextra}
```

It's an additional magic inside esmock, but I think we can have such magic for popular tools like Babel or Yarn.

**Comment by iambumblehead** [comment]
what do pnp-resolver.js sources look like?

**Comment by koshic** [comment]
> what do pnp-resolver.js sources look like?

https://github.com/iambumblehead/esmock/wiki#call-esmock-yarn-pnp - it's enough

**Comment by iambumblehead** [comment]
what do these sources look like? `import pnpapi from "pnpapi";` I searched and found this https://www.npmjs.com/package/pnpapi?activeTab=code but there are no sources listed there

**Comment by koshic** [comment]
I've updated esmock wiki recently, so resolver source is here:
<img width="1167" alt="image" src="https://github.com/iambumblehead/esmock/assets/20106607/0caeb7d1-b5b9-4162-9bca-f676e8feb2e1">

**Comment by koshic** [comment]
https://yarnpkg.com/advanced/pnpapi#requirepnpapi

<img width="964" alt="image" src="https://github.com/iambumblehead/esmock/assets/20106607/fdcd91a4-0442-4029-bbd5-6aa82a028d4f">

**Comment by iambumblehead** [comment]
Oh interesting, so esmock could support yarn pnp without adding any new dependencies...

If you make a PR that is good and if you don't I will make one over the next day or two. Imo a single unit test would be sufficient to start and a special ci job could be added for that.

**Comment by koshic** [comment]
Yep, I'll start right now.

**Comment by iambumblehead** [comment]
Not sure if this would work. Returns user-defined resolver, then tries yarn resolver finally returns resolvewithplus
_esmockReslover.js_
```javascript
import resolvewithplus from 'resolvewithplus'

export default async opts => opts.resolver
 || (await import('./pnp-resolver.js').catch(() => {})).default
 || resolvewithplus
```

**Comment by koshic** [comment]
PnP detection can be done via process.versions.pnp, which is faster and cleaner than trying to import non-existen'pnpapi'  module for classic setup.

What about order - yeah, we can skip 'getResolver' call if user-defined one already present in ops. Currently it not so important, but we can use dynamic load for resolvewithplus to avoid useless module load (and creating a lot of objects inside) via static import.

**Comment by koshic** [comment]
https://github.com/iambumblehead/esmock/pull/255

**Comment by iambumblehead** [comment]
okay its looking good at the PR :+1:
