### ISSUE TITLE
resolve error introduced with 2.5.2 

### ISSUE THREAD

**Issue by tripodsan** [iambumblehead/esmock#260]
we have a monorepo and use esmock in one of the npm workspaces: https://github.com/adobe/helix-shared/tree/main/packages/helix-shared-bounce

https://github.com/adobe/helix-shared/blob/ed6523ad6cced4d55db00edf76081e61f463ff28/packages/helix-shared-bounce/test/bounce.test.js#L170-L174

but since version 2.5.2, we get this error:

```
     Error: ENOENT: no such file or directory, realpath './src/index.js'
```

version:
```
$ npm ls esmock
@adobe/helix-shared-monorepo@1.0.0 
└─┬ @adobe/helix-shared-bounce@2.0.11 -> ./packages/helix-shared-bounce
  └── esmock@2.5.2
  ```

**Comment by tripodsan** [comment]
I moved the code to its own project, and the error still occurs.... so it is not related to the monorepo.

**Comment by koshic** [comment]
<img width="747" alt="image" src="https://github.com/iambumblehead/esmock/assets/20106607/b50baa48-a5fa-4edf-82ce-ac484ad3cc39">

@tripodsan as you can see, issue is related to `@adobe/fetch` resolving (tested with esmock 2.5.6). I'll continue investigation.

**Comment by koshic** [comment]
esmock resolver can't properly handle that combination of `main`, `module` and `type: module`
<img width="339" alt="image" src="https://github.com/iambumblehead/esmock/assets/20106607/2396033c-aa42-4300-addf-015811a7b9d8">

`main` field totally ignored, `module` handled incorrectly. CC @iambumblehead

**Comment by iambumblehead** [comment]
a couple of different versions of the loader have been published since the last esmock was published... let's try publishing with the latest loader and see if that resolves the issue

**Comment by iambumblehead** [comment]
recently using the resolver to process import trees with thousands of modules has surfaced a lot of little issues lately,

**Comment by iambumblehead** [comment]
I believe I've found the issue... pushing changes to the resolver repo soon

**Comment by iambumblehead** [comment]
https://github.com/iambumblehead/resolvewithplus/pull/64

**Comment by iambumblehead** [comment]
@tripodsan thanks for finding and reporting the issue -- if there are any problems please open or reopen any issue
