### ISSUE TITLE
Error when mocking a file that exports an array.

### ISSUE THREAD

**Issue by altearius** [iambumblehead/esmock#265]
I am getting a syntax error when using `esmock` to mock a file that exports an array.  I've created a PR that introduces a failing unit test demonstrating the issue: https://github.com/iambumblehead/esmock/pull/264

Please let me know if I am using `esmock` in an unintended fashion.

If this usage is supposed to be supported, and you decide this is a legit bug, I'm happy to work on it as time allows, if you would like to provide some direction as to how you would like this fixed. Time may or may not allow.

**Comment by iambumblehead** [comment]
thanks @altearius the newest version of esmock published a few moments ago should support Array-type default export
