### ISSUE TITLE
Unexpected strict mode reserved word syntax error when mocking express

### ISSUE THREAD

**Issue by lcapel** [iambumblehead/esmock#284]
Hello, I'm having a little bit of trouble when it comes to mocking `express`. When I attempt to do so I get a `SyntaxError` telling me that I'm using and unexpected strict mode reserved word.

I'm using node 20 and `mocha` as the testing framework.

I have no issues mocking other libraries, just `express`. I made this minimal example in codesanbox.io to illustrate the issue: https://codesandbox.io/p/devbox/busy-pare-xfv7gy

**Comment by iambumblehead** [comment]
@lcapel sorry for the delayed response adding this to the mock object that is produced from express allows the test to pass `delete def.static`

the exported "static" value is here, [link](https://github.com/expressjs/express/blob/master/lib/express.js#L81)
```javascript
exports.static = require('serve-static');
```

**Comment by lcapel** [comment]
@iambumblehead thank you for the quick fix everything is working as expected now!
