### ISSUE TITLE
incompatible with eslint-plugin-import

### ISSUE THREAD

**Issue by olsonpm** [iambumblehead/esmock#288]
Due to a top-level await in pnpResolver.js, eslint-plugin-import is unable to parse this module.

I understand if you don't want to support this use-case, as the owner of that module is particularly against native esm.  However if pnp is able to be imported directly now or if there's some other way to work around the top level await then that would be helpful.

For now I'm removing pnp in a fork since I have no plans on using yarn's pnp.

Thanks for this library :)

**Comment by koshic** [comment]
@olsonpm, eslint-plugin-import has no parser, eslint has it. And eslint supports top-level await without any issues. Could you please provide a more details / steps to reproduce?

Generally speaking, it's ok to fix some library a bit to provide compatibility with popular tools, but we need to understand the root cause.

**Comment by olsonpm** [comment]
Here's a reproduction

```sh
$ git clone git@github.com:olsonpm/repro.git
$ cd repro
$ git checkout esmock-issue-288
$ npm ci
$ npx eslint index.mjs

/path/to/repro/index.mjs
  1:20  error    Parse errors in imported module 'esmock': Unexpected token import (1:840)  import/namespace
  1:20  error    Parse errors in imported module 'esmock': Unexpected token import (1:840)  import/default
  1:20  warning  Parse errors in imported module 'esmock': Unexpected token import (1:840)  import/no-named-as-default
  1:20  warning  Parse errors in imported module 'esmock': Unexpected token import (1:840)  import/no-named-as-default-member

✖ 4 problems (2 errors, 2 warnings)
```

I'll look into the parser detail you mention to better understand the issue

**Comment by olsonpm** [comment]
looks like I needed to add `ecmaVersion: 2022` or later so you were right, it had to do with my configuration of the eslint parser.

I haven't encountered this issue before I think because typically eslint rules are specific to a projects' own files.  Looks like the import plugin parses other module's files (necessarily of course), which then means the parser configuration needs to support other library's code.

Sorry for the noise
