### ISSUE TITLE
No support for subpath patterns?

### ISSUE THREAD

**Issue by dschnare** [iambumblehead/esmock#289]
Esmock seems to have trouble resolving modules from packages with "exports" that use subpath patterns.

Some package (my-pack)
```
{
  "exports": {
    "./*": {
     "default": "./src/*/index.js",
     "types": "./types/*/index.d.ts"
    }
  }
}
```

Then in another package for example.
```
import { Something } from 'my-pack/stuff' // this line fails due to module ID not being found
```

**Comment by dschnare** [comment]
Reference: https://nodejs.org/docs/latest-v18.x/api/packages.html#subpath-patterns

**Comment by dschnare** [comment]
Interestingly, this error only occurs for me for some subpaths and not others from a package. To workaround I had to use the pattern to catch most subpaths then have an explicit export for subpaths that cause the error.

```
{
  "exports": {
    "./*": {
     "default": "./src/*/index.js",
     "types": "./types/*/index.d.ts"
    },
    "./my-path": {
      "default": "./src/my-path/index.js",
      "types": "./src/my-path/index.d.ts"
    }
  }
}
```

**Comment by iambumblehead** [comment]
@dschnare subpaths are supported and if one is not resolved correctly that's a bug. esmock uses [resolvewithplus][1] to resolve module ids, so that's were the solution should happen.

Node's dsl esm pattern language is tricky to parse. For resolvewithplus, official node examples were copied to unit-tests used by resolvewithplus and when missing cases have been discovered they've been resolved in new versions of resolvewithplus

[1]: https://github.com/iambumblehead/resolvewithplus

**Comment by iambumblehead** [comment]
@dschnare I have not seen wildcard export namespace names before, eg `{"exports":{"./namepace*": { ... }}}` that usage does not appear to be documented at the link you shared.

**Comment by dschnare** [comment]
Wildcard no, but using the asterisk to match a folder works and documented. It’s a weird thing to have most of the folders match and only a few give issues but that’s what is happening for sure. Anyway, I do have a work around but less than ideal.

Thanks for responding so quickly. When u have time I will investigate the package you mentioned and see if I can repro in a simple example.

**Comment by iambumblehead** [comment]
@dschnare thanks for reporting. Its always good to learn about these cases I didn't know about.

**Comment by iambumblehead** [comment]
@dschnare is this what you think the exports, directory and file layout should look like for unit-testing this?
```json
{
  "name": "asterisk-dir-name",
  "type": "module",
  "exports": {
    "./*": {
      "default": "./src/*/index.js",
      "types": "./types/*/index.d.ts"
    }
  }
}
```

```bash
.
├── package.json
├── src
│   └── mystuff
│       └── index.js
└── types
    └── mystuff
        └── index.d.ts
```

**Comment by iambumblehead** [comment]
@dschnare I wonder specifically how the named-property asterisk and then its nested, matched value must correspond to each other and the specifier used to import such a module.

For example, should the outer "./*" return *any* directory or only a directory that corresponds with the imported moduleId?

Maybe we should first implement any basic solution and then refine that later as any edge-cases are reported to fail.

**Comment by iambumblehead** [comment]
@dschnare https://github.com/iambumblehead/resolvewithplus/pull/65

**Comment by dschnare** [comment]
That test scenario is perfect. That's what we have currently in our project. Some folders work, while others didn't so I had to specifically add an export for that folder.

**Comment by dschnare** [comment]
@iambumblehead It looks like from the documentation that the subpath pattern "./*" would match any path like "mymodule/something", "mymodule/something/cool", etc. And technically "*" could be included multiple times in the export pattern. This I didn't know, but interesting.

> All instances of * on the right hand side will then be replaced with this value, including if it contains any / separators.

**Comment by iambumblehead** [comment]
@dschnare the PR was just updated so that the tests will pass in windows. Feel free to recommend any changes

**Comment by dschnare** [comment]
@iambumblehead I understood that incorrectly. The `*` can appear multiple times on the right side. On the left side it appears it should only occur once.

**Comment by iambumblehead** [comment]
if the overall approach is okay (as it seems to be) its good for me if the PR is accepted. Later on, when needed, the place that expands the asterisks on the right side could be improved for supporting more situations.
