### ISSUE TITLE
Version 2.6.3 changed the way to mock libraries

### ISSUE THREAD

**Issue by Jeff-Tham** [iambumblehead/esmock#293]
Prior to version 2.6.3, the follow code snippet is working fine.

```js
    esmock(
        '../../../src/processMessages.js',
        {
          'app-utils/src/logger/logger': {
            logger: loggerStub,
          }
        }
      )
```

after upgrade version to 2.6.3, it produces follow error:
` Error: ENOENT: no such file or directory, realpath '/xxx/node_modules/app-utils/.js.js/src/logger/logger/*'` unknown `.js.js` included.

it expected to rewrite the code and pointed to the node_modules directory as:

```js
    esmock(
        '../../../src/processMessages.js',
        {
          '../../../node_modules/app-utils/src/logger/logger': {
            logger: loggerStub,
          }
        }
      )
```

FYI, the package.json for `app-utils` use this setting:
```json
  "files": [
    "src",
    "dist"
  ],
  "exports": {
    "./*": {
      "require": "./*.js",
      "import": "./*.js"
    }
  },
```

**Comment by iambumblehead** [comment]
night time here now but will take a look tomorrow

**Comment by iambumblehead** [comment]
@Jeff-Tham a solution should be ready in a few hours. This type of wildcard/glob expansion and matching is a "weak" area of esmock which will be improved as a result of this issue.  A hacky sort-of solution was implemented a few weeks back https://github.com/iambumblehead/esmock/issues/289 and the newer solution will be a little less hacky (imo)

**Comment by iambumblehead** [comment]
this should resolve the issue https://github.com/iambumblehead/resolvewithplus/pull/67

**Comment by iambumblehead** [comment]
@Jeff-Tham thanks for opening the issue. Awaiting replies to the PR....

**Comment by Jeff-Tham** [comment]
@iambumblehead , if you can publish a beta version, i can test it with my code. Thanks for the quick response!

**Comment by iambumblehead** [comment]
esmock@2.6.4 is published please reopen or open a new issue if there are any problems :)

**Comment by Jeff-Tham** [comment]
The bug is fixed.
Thanks @iambumblehead  for the great work. I really appreciate it.
