### ISSUE TITLE
Scoped mocks failing with pnpm but working with npm

### ISSUE THREAD

**Issue by darcyrush** [iambumblehead/esmock#302]
Ok, this is a was a weird issue to track down, but I have found an issue with either `esmock`, `pnpm`/`npm` or `tsimp`. I realize that's a lot of options for failure, but I thought I would start here since `esmock` reliably reproduces the issue.

Basically when mocking a scoped package installed via `pnpm`, the mock doesn't take effect. When the package is installed via `npm` the mock takes effect as expected.

Here is a minimal reproduction repository; https://github.com/darcyrush/esmock-scoped-package
```
# Works
rm -fr node_modules/ && npm i && npm run test

# Fails
rm -fr node_modules/ && pnpm i && npm run test
```
I haven't tested `yarn` as I'm not familiar with it, but I imagine it will work as it uses the same install logic as `npm`. (`pnpm` uses symlinking of packages)

```
Node 21.7.3
Ubuntu 22.04 Linux 5.15.0-105-generic x86_64
```

**Comment by iambumblehead** [comment]
Thanks for opening the issue. I don't use pnpm myself and the person who added pnpm support hasn't been around lately @koshic 

The main file using pnpm resolver is here https://github.com/iambumblehead/esmock/blob/main/src/pnpResolver.js

**Comment by iambumblehead** [comment]
the demo you made looks great and would probably be a good thing to copy into the esmock tests

There are many esmock tests, but currently no tests for pnpm specifically

**Comment by iambumblehead** [comment]
failed test output here looks like this btw
```bash
> test
> TSIMP_PROJECT=./test/tsconfig.json node --import tsimp/import --test-reporter spec --test 'test/example.test.ts'

[Nest] 48166  - 2024/05/03 7:56:54     LOG [NestFactory] Starting Nest application...
[Nest] 48166  - 2024/05/03 7:56:54   ERROR [ExceptionHandler] metatype is not a constructor
TypeError: metatype is not a constructor
    at Injector.instantiateClass (/home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/injector.js:365:19)
    at callback (/home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/injector.js:65:45)
    at async Injector.resolveConstructorParams (/home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/injector.js:144:24)
    at async Injector.loadInstance (/home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/injector.js:70:13)
    at async Injector.loadProvider (/home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/injector.js:97:9)
    at async /home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Promise.all (index 0)
    at async InstanceLoader.createInstancesOfProviders (/home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/instance-loader.js:55:9)
    at async /home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/instance-loader.js:40:13
    at async Promise.all (index 1)
✖ test/example.test.ts (2044.283154ms)
  'test failed'
```

**Comment by iambumblehead** [comment]
@darcyrush both conditions at this [pnpResolver.js](https://github.com/iambumblehead/esmock/blob/main/src/pnpResolver.js#L4) line fail
```javascript
const pnpapi = process.versions.pnp && (await import('pnpapi')).default
```
`process.versions.pnp` is `undefined` and `pnpapi` is not found when it is imported. Any ideas how to resolve?

**Comment by koshic** [comment]
@iambumblehead "pnp" (yarn feature, no node_modules on the disk) != "pnpm" (package manager), so undefined is expected.

**Comment by iambumblehead** [comment]
'nothing to add here, but any thoughts @darcyrush

**Comment by iambumblehead** [comment]
adding console.log to esmockModule.js shows the following (differing) paths are resolved for npm vs pnpm

**pnpm**
```javascript
{
  moduleId: '../src/example.js',
  fileURL: 'file:///home/bumble/software/esmock-scoped-package/src/example.ts'
}
{
  moduleId: '@nestjs/core',
  fileURL: 'file:///home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/index.js'
}
```

**npm**
```javascript
{
  moduleId: '../src/example.js',
  fileURL: 'file:///home/bumble/software/esmock-scoped-package/src/example.ts'
}
{
  moduleId: '@nestjs/core',
  fileURL: 'file:///home/bumble/software/esmock-scoped-package/node_modules/@nestjs/core/index.js'
}
```

Possibly the resolver follows true paths rather than symlink paths causing the issue. Possibly this could be resolved by updating the resolver to operate differently for pnpm.

**Comment by iambumblehead** [comment]
updating the pnpm variant to return the same paths as the npm variant, the tests fail with the same error `TypeError: metatype is not a constructor`
```javascript
{
  moduleId: '../src/example.js',
  fileURL: 'file:///home/bumble/software/esmock-scoped-package/src/example.ts'
}
{
  moduleId: '@nestjs/core',
  fileURL: 'file:///home/bumble/software/esmock-scoped-package/node_modules/@nestjs/core/index.js'
}
```

**Comment by iambumblehead** [comment]
Per the finding in the previous comment, the error occurs regardless of how esmock resolves the modules so my hunch is that a similar symlink/truepath thing affects tsimp which possibly causes the issue.

**Comment by darcyrush** [comment]
> failed test output here looks like this btw
> 
> ```shell
> > test
> > TSIMP_PROJECT=./test/tsconfig.json node --import tsimp/import --test-reporter spec --test 'test/example.test.ts'
> 
> [Nest] 48166  - 2024/05/03 7:56:54     LOG [NestFactory] Starting Nest application...
> [Nest] 48166  - 2024/05/03 7:56:54   ERROR [ExceptionHandler] metatype is not a constructor
> TypeError: metatype is not a constructor
>     at Injector.instantiateClass (/home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/injector.js:365:19)
>     at callback (/home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/injector.js:65:45)
>     at async Injector.resolveConstructorParams (/home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/injector.js:144:24)
>     at async Injector.loadInstance (/home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/injector.js:70:13)
>     at async Injector.loadProvider (/home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/injector.js:97:9)
>     at async /home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/instance-loader.js:56:13
>     at async Promise.all (index 0)
>     at async InstanceLoader.createInstancesOfProviders (/home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/instance-loader.js:55:9)
>     at async /home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/instance-loader.js:40:13
>     at async Promise.all (index 1)
> ✖ test/example.test.ts (2044.283154ms)
>   'test failed'
> ```

Yes, this is correct. Apologies, I should have stated that in the issue. The test and test case implementation itself is nonsensical, but I couldn't find a more simple name-spaced package to use as a better example.

@iambumblehead Thank you for taking the time to look into this. I will open a ticket in `tsimp` and link back to this issue.

**Comment by darcyrush** [comment]
failed test output here looks like this btw

    > test
    > TSIMP_PROJECT=./test/tsconfig.json node --import tsimp/import --test-reporter spec --test 'test/example.test.ts'

    [Nest] 48166  - 2024/05/03 7:56:54     LOG [NestFactory] Starting Nest application...
    [Nest] 48166  - 2024/05/03 7:56:54   ERROR [ExceptionHandler] metatype is not a constructor
    TypeError: metatype is not a constructor
        at Injector.instantiateClass (/home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/injector.js:365:19)
        at callback (/home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/injector.js:65:45)
        at async Injector.resolveConstructorParams (/home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/injector.js:144:24)
        at async Injector.loadInstance (/home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/injector.js:70:13)
        at async Injector.loadProvider (/home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/injector.js:97:9)
        at async /home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/instance-loader.js:56:13
        at async Promise.all (index 0)
        at async InstanceLoader.createInstancesOfProviders (/home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/instance-loader.js:55:9)
        at async /home/bumble/software/esmock-scoped-package/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_@nestjs+platform-express@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/injector/instance-loader.js:40:13
        at async Promise.all (index 1)
    ✖ test/example.test.ts (2044.283154ms)
      'test failed'

Yes, this is output for the test failing due to the mock not taking effect. Apologies, I should have stated that in the issue. The test and test case implementation itself is nonsensical, but I couldn't find a more simple name-spaced package to use as a better example.

Thank you for taking the time to look into this. Before opening an issue with `tsimp`, I wanted to see if other TS runners were affected so I added both `tsx` and `ts-node`. It appears they are all impacted by this, which makes me think this may still be related to `esmock`.

I updated the [minimal reproduction repository](https://github.com/darcyrush/esmock-scoped-package/blob/main/package.json) to help streamline the investigation.

**Comment by kylekirkby** [comment]
Hey all 👋

Did anyone find a fix for this by any chance?

Just hit this myself...

**Comment by iambumblehead** [comment]
It would be great if esmock would handle these pnpm situations. I haven't used pnpm and so there has not been an organic reason for me personally to resoilve this. esmock wraps the growing complexities of esm module resolution, loader behaviour, etc. and so, even for myself, fixing this issue is likely difficult.

**Comment by iambumblehead** [comment]
installing pnpm means downloading a binary and giving it access to your system (not nice)

**Comment by insanity54** [comment]
I'm sorry but there is not much logic in your comment about giving pnpm binary access to your system. You also give node and npm access to your system and where's the equitable complaint about that? We all give binaries access to our systems because those binaries do useful tasks for us. And why is it that the people who haven't tried a thing are the most critical of that thing? You haven't tried pnpm and that's fine, but why are you judging it as if you know what it's good at?

**Comment by iambumblehead** [comment]
I think this resolves the issue
```diff
diff --git a/src/esmockLoader.js b/src/esmockLoader.js
index 0b16977..51c3f11 100644
--- a/src/esmockLoader.js
+++ b/src/esmockLoader.js
@@ -25,9 +25,13 @@ const isnotfoundRe = /isfound=false/
 const iscommonjsmoduleRe = /^(commonjs|module)$/
 const isstrict3 = /strict=3/
 const hashbangRe = /^(#![^\n]*\n)/
+
+const moduleIdEsc = str =>
+  str.indexOf('+') >= 0 ? str.replace(/(?!\\)\+/g, '\\+') : str
+
 // returned regexp will match embedded moduleid w/ treeid
 const moduleIdReCreate = (moduleid, treeid) => new RegExp(
-  `.*(${moduleid}(\\?${treeid}(?:(?!#-#).)*)).*`)
+  `.*(${moduleIdEsc(moduleid)}(\\?${treeid}(?:(?!#-#).)*)).*`)
 
 // node v12.0-v18.x, global
 const mockKeys = global.mockKeys = (global.mockKeys || {})
```

@insanity54 thanks for chiming in, my apology for not being more careful with my message.

**Comment by iambumblehead** [comment]
I won't be around to finish this for at least a few hours...

**Comment by iambumblehead** [comment]
planning to merge and publish soon

**Comment by iambumblehead** [comment]
anyone participating or reading this thread, please report back and share your experience using pnpm with [esmock version 2.6.8+](https://github.com/iambumblehead/esmock/releases/tag/v2.6.8)
