### ISSUE TITLE
[Question] Is there a way to test sequential interactions?

### ISSUE THREAD

**Issue by insanity54** [iambumblehead/esmock#310]
Thank you for esmock. I was led here after I was unable to mock ESM modules using Sinon. I'm finding esmock very helpful.

I'm writing a module that spawns a CLI tool to make network requests. I want to write a test which ensures that my module gracefully handles errors by retrying the request.

I'm coming from the [sinon](https://sinonjs.org/releases/v18/stubs/) world where I'm used to being able to write stubs that behave differently every time they are called. For example

```js
stub.onFirstCall();
stub.onSecondCall();
stub.onThirdCall();
```

Is there any way to achieve something like this in esmock, where each call to the mocked module/function returns a different value? I'm imagining this stub could be the function which makes the request, and onFirstCall(), it returns an error message. Then onSecondCall(), it returns a success message.

**Comment by iambumblehead** [comment]
I have done this using the nodejs-provided mock/stub tools. Will take a look here to see if I can find it and if so, paste something here...

**Comment by iambumblehead** [comment]
The important part **`reqAuthServiceTokensPOST.mock.calls.length === 0`** The mock in this test returns a 403 the first time it is called, then a 200 for subsequent calls

```javascript
import test, { mock } from 'node:test'
import assert from 'node:assert/strict'
import { setTimeout } from 'node:timers/promises'
import nock from 'nock'
import esmock from 'esmock'

import mockLogger from '../helpers/mockLogger.js'
import mockToken from '../helpers/mockToken.js'

const TESTSERV_CLIENT_ID = 'thisserv-FUyetvDEVL1ykFEb64brg'
const TESTSERV_SECRET = 'd8edICt3mS6OJ18oYAkdG'

const env = {
  ...process.env,
  AUTH_SERVICE_HOST: 'http://auth-prod-service.ns-auth-prod',
  ISSUERS_WHITELIST: [mockToken.DEF_CLIENT_ISS],
  CLIENTS_WHITELIST: [],
  CLIENTS_VERIFY_ISHARD: false,
  CLIENT_AUTH_DETAILS: {
    client_id: TESTSERV_CLIENT_ID,
    client_secret: TESTSERV_SECRET
  }
}

test.beforeEach(nock.disableNetConnect)

test('envSessTokensFresh retries', async () => {
  const returnedToken = await mockToken()
  const reqAuthServiceTokensPOST = mock.fn(() =>
    reqAuthServiceTokensPOST.mock.calls.length === 0 ? ({
      status: 403
    }) : ({
      status: 200,
      body: {
        expires_in: mockToken.DEF_EXPIRESMS,
        access_token: returnedToken
      }
    })
  )

  const {
    envSessTokensFresh
  } = await esmock('../../src/env/envSess.js', {
    '../../src/env/envLogger.js': mockLogger(),
    '../../src/req.js': { reqAuthServiceTokensPOST },
    '../../src/env/env.js': {
      ...env,
      AUTH_SERVICE_TOKEN_TRIESMS: 100
    }
  })

  const start = Date.now()
  const tokens = await envSessTokensFresh()

  // at least ~4 second delay between first and second try
  assert.ok(Date.now() - start >= 100)
  assert.deepEqual(tokens, {
    ...tokens,
    access_token: returnedToken
  })

  // clear timeout to free process
  envSessTokensFresh(false)
})
```

**Comment by iambumblehead** [comment]
thanks for the star and message :) feel free to re-open for any reason
