### ISSUE TITLE
Error: modulePath not found: "../../lib/init/config-file.js"

### ISSUE THREAD

**Issue by aladdin-add** [iambumblehead/esmock#41]
the gh actions passed, but we've got the error when releasing.
job log: https://jenkins.eslint.org/job/Releases/job/eslint-create-config%20Release/1/console

I just noticed there is a space(%20) in the dirname. maybe this is the cause?
```sh
     Error: modulePath not found: "../../lib/init/config-file.js"
      at esmockModuleMock (file:///var/lib/jenkins/workspace/Releases/eslint-create-config%20Release/create-config/node_modules/esmock/src/esmockModule.js:152:11)
      at async esmock (file:///var/lib/jenkins/workspace/Releases/eslint-create-config%20Release/create-config/node_modules/esmock/src/esmock.js:20:25)
      at async Context.<anonymous> (file:///var/lib/jenkins/workspace/Releases/eslint-create-config%20Release/create-config/tests/init/config-file.js:82:43)
```

**Comment by iambumblehead** [comment]
interesting. I'll try to add a test that catches this.

**Comment by iambumblehead** [comment]
thanks for reporting @aladdin-add

**Comment by iambumblehead** [comment]
I did find a whitespace-related error with a test. I'll push up changes soon.

**Comment by iambumblehead** [comment]
when file name that comes into the module loader has encoded whitespaces

**Comment by iambumblehead** [comment]
@aladdin-add the PR is here https://github.com/iambumblehead/esmock/pull/42 if you're around to review that would be awesome, otherwise I'll probably merge as-is and publish to expedite the changes for you

**Comment by iambumblehead** [comment]
the error I caught is slightly different from the one you reported. I did not see the 'modulePath' not found error but will try to reproduce that in the PR next.

**Comment by iambumblehead** [comment]
I renamed the directory holding esmock to include whitespace and the tests file :)

**Comment by aladdin-add** [comment]
actually, there is another error like `Error: not a valid path: "../../lib/shared/logging.js"`. I can repro the error when renaming the project dir from `create-config` to `create config`.

just tried the commit: `github:iambumblehead/esmock#f91a8e053444c7bb5e4159d974b165e6eb544ce6`, however it did not work.

**Comment by iambumblehead** [comment]
@aladdin-add another change coming to that PR in a minute or two that might resolve the issue
