### ISSUE TITLE
support typescript [basic support is working]

### ISSUE THREAD

**Issue by GalRab** [iambumblehead/esmock#48]

**Comment by iambumblehead** [comment]
@GalRab I'm not sure if typescript can be supported now because typescript tests require "--loader=ts-node/esm" and there is not currently a way to use both loaders for one node process, "ts-node/esm" and "esmock" https://github.com/nodejs/modules/issues/513

I tried a little test using this command,
```bash
ava --node-arguments=\"--loader=ts-node/esm --loader=esmock --experimental-specifier-resolution=node\" ./spec/ava-ts/*.spec.ts
```

I get errors like these depending upon if --experimental-specifier-resolution=node is included or not. below, without --experimental-specifier-resolution=node,
```bash
  Uncaught exception in spec/ava-ts/esmock.ava.spec.ts

  TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/bumble/software/esmock/spec/ava-ts/esmock.ava.spec.ts
```

and with --experimental-specifier-resolution=node
```bash
  Uncaught exception in spec/ava-ts/esmock.ava.spec.ts

  RangeError [ERR_UNKNOWN_MODULE_FORMAT]: Unknown module format: null for URL file:///home/bumble/software/esmock/spec/ava-ts/esmock.ava.spec.ts
```

ideas or suggestions are welcome

**Comment by iambumblehead** [comment]
@GalRab would you create a branch that has a single, passing typescript test inside the esmock sources? inside a file such as "spec/ava-ts/esmock.ava.spec.ts"? Try to include the most minimal setup and smallest tsconfig.json file possible.

I'm not too familiar with typescript at the moment but if you'll give me the good starting point maybe I can find a solution...

**Comment by iambumblehead** [comment]
@GalRab I've managed to get a working typescript test in local esmock sources, but when I include the additional esmock loader "--loader=esmock" there's a runtime error,
```bash
  TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/bumble/software/esmock/spec/ava-ts/esmock.ava.spec.ts
```
I'm not sure how to resolve this, but in this case, esmock's "getSource" loader is not processing .ts file and simply passes the getSource arguments to node's native getSource loader.

**Comment by iambumblehead** [comment]
some notes for myself in case I need to try this again later...


_package.json_
```diff
diff --git a/package.json b/package.json
index f80be59..7829243 100644
--- a/package.json
+++ b/package.json
@@ -52,13 +52,21 @@
     "ava": "^4.0.1",
     "eslint": "^8.0.1",
     "form-urlencoded": "4.2.1",
+    "ts-node": "10.7.0",
+    "typescript": "4.1.3",
     "sinon": "^12.0.1"
   },
   "scripts": {
+    "test-ts": "ava --node-arguments=\"--loader=ts-node/esm --loader=./src/esmockLoader.mjs\" ./spec/ava-ts/*.spec.ts",
     "test-ava": "ava --node-arguments=\"--loader=./src/esmockLoader.mjs\" ./spec/ava/*.spec.js",
     "test-uvu": "node --no-warnings --loader=./src/esmockLoader.mjs ./node_modules/uvu/bin.js ./spec/uvu/",
     "test": "npm run test-ava && npm run test-uvu",
     "test-no-warn": "ava --node-arguments=\"--loader=./src/esmockLoader.mjs --no-warnings\"",
     "lint": "eslint src/*js spec"
+  },
+  "ava": {
+    "extensions": {
+      "ts": "module"
+    }
   }
 }
```


_tsconfig.json_
```json
{
  "compilerOptions": {
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

**Comment by iambumblehead** [comment]
closing this but it could be re-opened in the future when typescript's module loader can be used with other loaders

**Comment by GalRab** [comment]
I'll leave it for now. but maybe it can be done by calling Javascript output as a workaround.

example:

`test("test", async (t) => {
  const main = await esmock("../dist/src/Check.js", {
    "../dist222/src/CheckSRC.js": {
      getData: () => Promise.resolve("mock1111"),
    },
  });
  t.is(await main.foo(), `foo2`);
});`
The path conatins **.js** and **../dist**

package.json:
` "test-ava": "ava --node-arguments=\"--loader=esmock\"",
...
"ava": {
    "files": [
      "dist/test/*.test.js"
    ]
  },
`

**Comment by iambumblehead** [comment]
@GalRab yes that should work

**Comment by cspotcode** [comment]
Check out @cspotcode/multiloader to use multiple loaders at the same time.

https://www.npmjs.com/package/@cspotcode/multiloader

Also follow along with node's loaders team, because they are adding support for multiple loaders to node:
https://github.com/nodejs/loaders

**Comment by larsthorup** [comment]
FYI: Since node@18.6 it appears that having multiple loaders is now supported: 

https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.6.0

**Comment by iambumblehead** [comment]
In experiments here, this sequence of events occurred when loading esm modules only
 1. `await import('file.mjs')` is called from the test stack
 2. `resolve( specifier, { parentURL: 'file.mjs' });` hook is called from the module loader stack
 3. `load( 'file.mjs' )` hook is called from the module loader stack
 4. 'file.mjs' is imported and control returns to the test stack

When cjs modules are loaded, the test stack instead continues before the resolve hook is called.

If esmock will load each unseen file twice -- the first load could be used to verify module type and return an empty file to complete a handshake, the second load could return the real file and its import tree with any mock definitions. Previous handshake results could be re-used if the file is seen again.

This behaivour could cause problems when chained with other loaders. It might also be something that could be disabled if other loaders might resolve the cjs-mjs part of the problem.

**Comment by iambumblehead** [comment]
node v18 loads both module types in the same way without any handshake or special cjs loading behaviour. A new version 2.0.0 could be released so that the current 1.8.0 version could support older node versions and the newer 2.0.0 version could support newer things like typescript.

**Comment by iambumblehead** [comment]
ava + typescript tests at esmock always fail. These tests try to use ts-node/esm,

<details><summary>load tests using NODE_OPTIONS, ts-node first<br />
using `NODE_OPTIONS='--loader=ts-node/esm --loader=esmock'`</summary>

```console
$ npm run test-ava-ts

> esmock@1.8.1 test-ava-ts
> NODE_OPTIONS='--loader=ts-node/esm --loader=esmock' ava ./spec/ava-ts/*.spec.ts

(node:162161) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Exception in PromiseRejectCallback:
/home/bumble/software/esmock/node_modules/ts-node/dist/esm.js:133
            return { format, source };

RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
/home/bumble/software/esmock/node_modules/ts-node/dist/esm.js:219
    const ret = await fn();
                      ^

RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at nextLoad (node:internal/modules/esm/loader:151:5)
    at /home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:255:45
    at addShortCircuitFlag (/home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:409:21)
    at load (/home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:239:12)
    at nextLoad (node:internal/modules/esm/loader:173:28)
    at /home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:255:45
    at addShortCircuitFlag (/home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:409:21)
    at load (/home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:239:12)
    at nextLoad (node:internal/modules/esm/loader:173:28)
    at /home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:255:45
```
</details>

<details>
<summary>load tests using NODE_OPTIONS, esmock first<br />
using `NODE_OPTIONS='--loader=esmock --loader=ts-node/esm'`</summary>

```console
$ npm run test-ava-ts

> esmock@1.8.1 test-ava-ts
> NODE_OPTIONS='--loader=esmock --loader=ts-node/esm' ava ./spec/ava-ts/*.spec.ts

(node:162260) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Exception in PromiseRejectCallback:
node:internal/modules/esm/loader:178
      return output;

RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at getOwnPropertyValueOrDefault (node:internal/validators:139:38)
    at __node_internal_ (node:internal/validators:156:24)
    at validateArgs (node:internal/modules/esm/loader:602:16)
    at nextLoad (node:internal/modules/esm/loader:155:7)
    at load (file:///home/bumble/software/esmock/src/esmockLoader.mjs:91:10)
    at nextLoad (node:internal/modules/esm/loader:173:28)
    at load (file:///home/bumble/software/esmock/src/esmockLoader.mjs:91:10)
    at nextLoad (node:internal/modules/esm/loader:173:28)
    at load (file:///home/bumble/software/esmock/src/esmockLoader.mjs:91:10)
    at nextLoad (node:internal/modules/esm/loader:173:28)
```
</details>


<details>
<summary>load tests using ava loader, ts-node first<br />
`npx ava --node-arguments="--loader=ts-node/esm --loader=esmock" ./spec/ava-ts/*.spec.ts`</summary>

```console
$ npx ava --node-arguments="--loader=ts-node/esm --loader=esmock" ./spec/ava-ts/*.spec.ts

(node:162016) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Exception in PromiseRejectCallback:
            return { format, source };
RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
    const ret = await fn();
RangeError: Maximum call stack size exceeded
  ✖ spec/ava-ts/esmock.ava.only.spec.ts exited due to an error:

  RangeError: Maximum call stack size exceeded

  RangeError: Maximum call stack size exceeded
      at /home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:255:45
      at addShortCircuitFlag (/home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:409:21)
      at load (/home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:239:12)
      at nextLoad (node:internal/modules/esm/loader:173:28)
      at /home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:255:45
      at addShortCircuitFlag (/home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:409:21)
      at load (/home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:239:12)
      at nextLoad (node:internal/modules/esm/loader:173:28)
      at /home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:255:45
      at addShortCircuitFlag (/home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:409:21)

  ─


node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
RangeError [Error]: Maximum call stack size exceeded
    at /home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:255:45
    at addShortCircuitFlag (/home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:409:21)
    at load (/home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:239:12)
    at nextLoad (node:internal/modules/esm/loader:173:28)
    at /home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:255:45
    at addShortCircuitFlag (/home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:409:21)
    at load (/home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:239:12)
    at nextLoad (node:internal/modules/esm/loader:173:28)
    at /home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:255:45
    at addShortCircuitFlag (/home/bumble/software/esmock/node_modules/ts-node/src/esm.ts:409:21)

Node.js v18.6.0
```
</details>


<details>
<summary>load tests using ava loader, esmock first<br />
`npx ava --node-arguments="--loader=esmock --loader=ts-node/esm" ./spec/ava-ts/*.spec.ts`</summary>

```console
$ npx ava --node-arguments="--loader=esmock --loader=ts-node/esm" ./spec/ava-ts/*.spec.ts

(node:162081) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Exception in PromiseRejectCallback:
  return nextLoad(url, context, nextLoad);
RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
      const output = await ReflectApply(hook, undefined, args);
RangeError: Maximum call stack size exceeded
  ✖ spec/ava-ts/esmock.ava.only.spec.ts exited due to an error:

  RangeError: Maximum call stack size exceeded

  RangeError: Maximum call stack size exceeded
      at String.replace (<anonymous>)
      at load (file:///home/bumble/software/esmock/src/esmockLoader.mjs:72:13)
      at nextLoad (node:internal/modules/esm/loader:173:28)
      at load (file:///home/bumble/software/esmock/src/esmockLoader.mjs:91:10)
      at nextLoad (node:internal/modules/esm/loader:173:28)
      at load (file:///home/bumble/software/esmock/src/esmockLoader.mjs:91:10)
      at nextLoad (node:internal/modules/esm/loader:173:28)
      at load (file:///home/bumble/software/esmock/src/esmockLoader.mjs:91:10)
      at nextLoad (node:internal/modules/esm/loader:173:28)
      at load (file:///home/bumble/software/esmock/src/esmockLoader.mjs:91:10)

  ─


node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
RangeError [Error]: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at load (file:///home/bumble/software/esmock/src/esmockLoader.mjs:72:13)
    at nextLoad (node:internal/modules/esm/loader:173:28)
    at load (file:///home/bumble/software/esmock/src/esmockLoader.mjs:91:10)
    at nextLoad (node:internal/modules/esm/loader:173:28)
    at load (file:///home/bumble/software/esmock/src/esmockLoader.mjs:91:10)
    at nextLoad (node:internal/modules/esm/loader:173:28)
    at load (file:///home/bumble/software/esmock/src/esmockLoader.mjs:91:10)
    at nextLoad (node:internal/modules/esm/loader:173:28)
    at load (file:///home/bumble/software/esmock/src/esmockLoader.mjs:91:10)

Node.js v18.6.0
</details>

@cspotcode when adding a typescript-test to esmock the ts-node/esm and esmock loaders cannot be used together and the errors above are shown. Do you have any ideas for resolving this?

It seems that [both loaders][0] use return `shortCircuit : true` which might prevent chaining them together. What do you think?

[0]: https://github.com/TypeStrong/ts-node/blob/main/src/esm.ts#L412

**Comment by iambumblehead** [comment]
@cspotcode `shortCircuit : true` can be removed from esmock master branch sources and the tests still pass. nextLoad needs to be called instead and this seems fine as far as the esmock behaviour goes

**Comment by iambumblehead** [comment]
I'm able to load this test file with this command: `node --no-warnings --loader=ts-node/esm --test ./main.test.ts`

_main.test.ts_
```javascript
import test from 'node:test';
import assert from 'node:assert/strict';
//import esmock from 'esmock';

test('should load a test', async () => {
    assert.strictEqual( true, true );
});
```
but if I un-comment the esmock import there is an error
```
not ok 1 - /home/bumble/software/ts-node-fail-demo/main.test.ts
  ---
  duration_ms: 0.622327126
  failureType: 'subtestsFailed'
  exitCode: 1
  stdout: ''
  stderr: |-
    /home/bumble/software/ts-node-demo/node_modules/ts-node/src/index.ts:859
        return new TSError(diagnosticText, diagnosticCodes, diagnostics);
               ^
    TSError: ⨯ Unable to compile TypeScript:
    main.test.ts(3,20): error TS7016: Could not find a declaration file for module 'esmock'. '/home/bumble/software/ts-node-demo/node_modules/esmock/src/esmockLoader.mjs' implicitly has an 'any' type.
      Try `npm i --save-dev @types/esmock` if it exists or add a new declaration (.d.ts) file containing `declare module 'esmock';`
```
I'm not very familiar with typescript but maybe this is getting close

**Comment by iambumblehead** [comment]
@cspotcode generally the loading behaviour and sequence used with cjs modules is different from that used by mjs modules. Politely, it seems possible, based on my experience with both formats, that there are problems because ts-node uses a cjs module for its module loader.

**Comment by iambumblehead** [comment]
I tried using esbuild, which does export an esm module, and the same recursive loader calls occurred there also,
```console
node --no-warnings --loader @esbuild-kit/esm-loader --loader=esmock --test ./main.test.ts
```

**Comment by iambumblehead** [comment]
@cspotcode I believe the issues above originates from esmock because, when using diferent combinations of loaders, combinations that include esmock always fail with this recursive load hook error

**Comment by iambumblehead** [comment]
@cspotcode update! ts-node and esmock are both working together locally!

**Comment by cspotcode** [comment]
Sounds good.  I was pinged on a bunch of these messages, but just to clarify, ts-node does not need to make any code changes, correct?

**Comment by iambumblehead** [comment]
@cspotcode I apologize for pinging you many times and will stop. No changes are needed.

**Comment by iambumblehead** [comment]
initial typescript support is ready at this PR https://github.com/iambumblehead/esmock/pull/68

**Comment by iambumblehead** [comment]
@larsthorup @GalRab if you have a chance to test esmock with typescript please share your experience,
```console
node --loader=ts-node/esm --loader=esmock --test *ts
```

**Comment by larsthorup** [comment]
@iambumblehead thank you for quickly releasing a fix for this. I don't use transpilation much myself, my interest in esmock and multiple loaders stems from experiments building a modular testing tool, where mocking would be handled by esmock and watch-mode would be handled by another loader, so this fix allows me to continue these experiments.
