### ISSUE TITLE
not working on node.js v17.8.0

### ISSUE THREAD

**Issue by aladdin-add** [iambumblehead/esmock#49]
see the log: https://github.com/eslint/create-config/runs/5709601942?check_suite_focus=true.

the weird thing is I didn't see how it is affected in node.js' changelog. (#_<-)

**Comment by iambumblehead** [comment]
@aladdin-add thanks for messaging me. I took a quick look now and it looks like node's native resolve hook, used by esmock, is updated to return a promise so after making this change the tests all pass again
```diff
-  const resolved = defaultResolve(specifier, context, defaultResolve);
+  const resolved = await defaultResolve(specifier, context, defaultResolve);
```

I'll publish the change soonish

**Comment by iambumblehead** [comment]
@aladdin-add feel free to re-open if you encounter any issue :)
