### ISSUE TITLE
Mocked dependency still gets evaluated

### ISSUE THREAD

**Issue by BadIdeaException** [iambumblehead/esmock#51]
I have the following `beforeEach` hook in a mocha test suite:
```
beforeEach(async function() {
	execa = sinon.stub().resolves();
	({ update } = await esmock('../../src/init/update.js', {}, {
		execa: { execa },
		'../../src/init/config.js': {
			default: config,
			paths
		}
	}));
});
```
However, file `config.js` still gets evaluated - if I insert a `console.log` statement I can see the output. This is not intended behavior, or is it? <strike>At least, this never happened until recently. Might it have something to do with the fix to #49?</strike> I am on NodeJS 17.9.0 and esmock 1.7.5. 

**EDIT:**
My bad for the part about this being new. That was actually on me...
Still, I'm a little surprised to see `config.js` gets loaded. I thought the point mocking it was that it wouldn't?

**Comment by iambumblehead** [comment]
https://github.com/iambumblehead/esmock/blob/master/src/esmockModule.js#L97-L98

@BadIdeaException esmock currently does something like this paraphrased example,
```javascript
const originalFile = import( pathtooriginalfile );
const mockedFile = Object.assign({}, originalFile, mockDefinitions);

return mockedFile
```

**Comment by BadIdeaException** [comment]
Ah, I see. I think I misunderstood a little bit what esmock was supposed to do then. I thought it replaced an entire _module_ with a mock, but it actually replaces specific _exports_ of a module. 

Thank you for clearing that up for me so quickly. I will close this issue then. Cheers.
