### ISSUE TITLE
support NODE_OPTIONS

### ISSUE THREAD

**Issue by cjroebuck** [iambumblehead/esmock#52]
currently you need to pass `--loader=esmock` as an argument to node because [esmock checks only process.argv](https://github.com/iambumblehead/esmock/blob/master/src/esmockLoader.mjs#L7-L8). 

It would be good to support NODE_OPTIONS env var too.

**Comment by iambumblehead** [comment]
@cjroebuck would you show how esmock should be started with NODE_OPTIONS? maybe support could be added.

**Comment by cjroebuck** [comment]
It would be something like: 

`NODE_OPTIONS='--loader=esmock' node src/whatever.js`

Thank you very much for esmock

**Comment by iambumblehead** [comment]
related https://github.com/TypeStrong/ts-node/discussions/1748
