### ISSUE TITLE
notes to consider adding minification to the publish step

### ISSUE THREAD

**Issue by iambumblehead** [iambumblehead/esmock#71]
here are the results from running a command like this on files in src
```console
$ npx esbuild ./src/esmockModule.js --minify --outfile=./mini/esmockModule.js

$ ls -l ./src
total 56
-rw-r--r--  1 bumble  staff    96B Jul 19 13:36 esmock.d.ts
-rw-r--r--  1 bumble  staff   1.5K Jul 19 13:36 esmock.js
-rw-r--r--  1 bumble  staff   888B Jul 19 13:35 esmockCache.js
-rw-r--r--  1 bumble  staff   209B Jul 19 13:36 esmockIsLoader.js
-rw-r--r--  1 bumble  staff   3.6K Jul 19 13:43 esmockLoader.mjs
-rw-r--r--  1 bumble  staff   6.5K Jul 19 13:35 esmockModule.js

$ ls -l ./mini 
total 32
-rw-r--r--  1 bumble  staff   731B Jul 20 09:14 esmock.js
-rw-r--r--  1 bumble  staff   427B Jul 20 09:14 esmockCache.js
-rw-r--r--  1 bumble  staff   184B Jul 20 09:14 esmockIsLoader.js
-rw-r--r--  1 bumble  staff   2.5K Jul 20 09:15 esmockModule.js
```

| **name**        | **src**           | **mini**  | **difference** |
| ------------- | ------------- | ----- | ---- |
| _esmock.js_     | 1500 | 731 | **769** |
| _esmockCache.js_      | 888      |   427 |  **661** |
| _esmockLoader.js_ | 209      |    184 | **25** |
| _esmockModule.js_ | 6500   |    2500 | **4000** |
| _total_ | | | _**5455**_ |

This micro-optimisation could reduce [final download size][0] from 31.8kb to, possibly, around ~26.3kb. Perhaps the size could be reduced furter If the loader and resolvewith package were minified. Its also possible the final package size would not change much, if minification reduces the effectiveness of tar compression used by npm.

[0]: https://packagephobia.com/result?p=esmock

**Comment by iambumblehead** [comment]
minifying resolvewithplus.js reduces size from 7.0K to 2.2K, total difference **4800.**

Another optimisation would move unit-test script commands from package.json into the test folders ignored by the npm publish step, things like these:

```json
{
    "test-node-ts": "node --no-warnings --loader=ts-node/esm --loader=esmock --test ./spec/node-ts/*ts",
    "test-node": "node --no-warnings --loader=esmock --test ./spec/node/",
    "test-node18": "npm run test-node && npm run test-node-ts",
    "test-nodeis18": "if (node -v | grep v18); then npm run test-node18; fi;",
    "test-ava": "npx ava --node-arguments=\"--loader=esmock\" ./spec/ava/*.spec.js",
    "test-uvu": "node --loader=esmock ./node_modules/uvu/bin.js ./spec/uvu/",
    "test:default": "npm run test-nodeis18 && npm run test-ava && npm run test-uvu",
    "test:windows": "npm run test-ava && npm run test-uvu"
}
```

**Comment by iambumblehead** [comment]
_another micro-optimisation_ would be to switch the license from MIT to ISC to reduce size from 1.1k to 750, _total difference 350._

**Comment by iambumblehead** [comment]
I'll add to and update this list as things are made smaller,


**esmock's install size is reduced from 31.8kB [to 25.67kB][0]**
  * **-6.13kB,** using minification steps [to shrink resolvewithplus][1]


[0]: https://packagephobia.com/result?p=esmock
[1]: https://github.com/iambumblehead/esmock/pull/72

**Comment by iambumblehead** [comment]
closing this. release page is here https://github.com/iambumblehead/esmock/releases/tag/v1.8.4

**Comment by iggyzap** [comment]
Total horror to debug mocking error with minification.

**Comment by iambumblehead** [comment]
@iggyzap delete the npm-published esmock from node_modules, then clone the github esmock in its place
```shell
your-project$ cd node_modules && rm -rf esmock && git clone https://github.com/iambumblehead/esmock
your-project/node_modules$ cd esmock && npm install
```
