### ISSUE TITLE
TypeError: Cannot add property default, object is not extensible

### ISSUE THREAD

**Issue by tripodsan** [iambumblehead/esmock#91]
with the upgrade to 1.8, I get:

```
TypeError: Cannot add property default, object is not extensible
    at x (file:///.../node_modules/esmock/src/esmockModule.js:1:802)
```

```js
return!c&&w(n.default)&&(n.default.default=n.default)
```

- trying to mock `@aws-sdk/client-sns`
- with 1.7.8, it still works fine. also note that I use a partial mock. 
- node v16.16

**Comment by tripodsan** [comment]
I added a `console.log(n)` to the minified code:
```
{
  getNotifier: [Function: getNotifier],
  default: [Module: null prototype] { getNotifier: [Function: getNotifier] }
}
```

it doesn't look like it comes from `@aws-sdk/client-sns`

**Comment by tripodsan** [comment]
the mock looks like:

```
   const proxyPublish = await esmock.px('../../src/index.js', {
      '../../src/support/notifications.js': await esmock.px('../../src/support/notifications.js', {
        '@aws-sdk/client-sns': {
          SNSClient: class {
            send(cmd) {
            }
          },
        },
      }),
    });
```

and `notifications.js` contains (no default export):

```
import { PublishCommand, SNSClient } from '@aws-sdk/client-sns';

class NotificationsSupport {
....
}

export function getNotifier(ctx) {
  ...
}
```

**Comment by iambumblehead** [comment]
@tripodsan thanks for opening this issue. If you would PR-add a test-case to any of the test runner folders [here,][0] I could resolve the issue sooner. From esmock's root folder use `npm install && npm run test:install` to fetch all dependencies needed, then from whichever test folder is being used, `npm test` will run tests.

The error might [originate here,][1] but it might be challenging for me to reproduce the issue.

If you create a PR with a failing test, I will be glad to merge it right away and try to resolve the issue.

[0]: https://github.com/iambumblehead/esmock/tree/master/tests
[1]: https://github.com/iambumblehead/esmock/blob/master/src/esmockModule.js#L57-L63

**Comment by iambumblehead** [comment]
@tripodsan the error is reproduced in a test [added at the PR here][0] but the test would be incomplete because I'm not sure what the success condition should look like

[0]: https://github.com/iambumblehead/esmock/pull/92

**Comment by tripodsan** [comment]
> Would you fix the PR to have a correct test condition?

ok. I'll have a look. thanks so far

**Comment by iambumblehead** [comment]
@tripodsan btw I think this is the solution
```diff
diff --git a/src/esmockModule.js b/src/esmockModule.js
index 79c6949..095d838 100644
--- a/src/esmockModule.js
+++ b/src/esmockModule.js
@@ -59,7 +59,7 @@ const esmockModuleApply = (definitionLive, definitionMock, definitionPath) => {
   // note: core modules do not define "default.default"
   //   import package from 'package';
   //   package.default(); <- extra default definition
-  if (!isCorePath && isObjOrFn(definition.default))
+  if (!isCorePath && Object.isExtensible(definition.default))
     definition.default.default = definition.default;
 
   return definition;
```
if we could update the test to hone in on this area specifically, without the aws client dependency that would be awesome.

**Comment by tripodsan** [comment]
I added a PR to your PR: https://github.com/iambumblehead/esmock/pull/93

which uses a simpler version (without sns). 

but I wasn't able to reproduce the error with the `constructor` that I had above...

**Comment by iambumblehead** [comment]
@tripodsan the changes are published.

Feel free to re-open this issue of the problem is not resolved or for any reason really
